### ISSUE TITLE
(Java) Code not highlighted

### ISSUE THREAD

**Issue by Alienah** [highlightjs/highlight.js#3605] opened 2022-08-29 15:36 UTC
**Describe the issue**
In some java snippets only the comment is being highlighted

**Which language seems to have the issue?**
 The language of the snippet is java

**Are you using `highlight` or `highlightAuto`?**
 We are using highlightElement over each code element
...

**Sample Code to Reproduce**
List<HandbrakeLever&gt> handbrakeLevers = findAllCars.stream()
    .map(Car::getHandbrakeLever) // Not all cars may have this
    .filter(Objects::nonNull)
    .toList();

Screenshot:

![image](https://user-images.githubusercontent.com/33132944/187237951-0558db5b-a43b-4a4b-9f1d-8e1b4c811ac4.png)

**Expected behavior**

I would expect some highlight, but only the comment is highlighted. In this example we see how visual studio code highlight this snippet

![image](https://user-images.githubusercontent.com/33132944/187237291-da902a9c-5f5e-4133-ba99-09326b749e8d.png)

**Additional context**
The library does highlight the parts of the code that are shown in your demos, that is, it is applying the highlighting in other types of examples.

If you could help me find a way to improve the highlighting with some configuration, I would appreciate it. I have tried adding the _ignoreIllegals_ option, but I don't know if I am doing it wrong or if it doesn't really apply to my issue.

Thanks in advance

**Comment by joshgoebel** [comment] 2022-08-29 15:55
Are classes in Java always capped/camel-case?

---

The Java grammar is [currently] pretty simple.  We currently do not highlight `.` properties, random variables (not sure how we'd know they were variables), or classes.   Not sure what demo you are looking at but the existing behavior is "correct" [ie, the current state of the software, not a bug] - though we'd certainly love if it was improved.  

Other languages do indeed have better highlighting support for some of these grammatical features. See #2500.

_If you'd want to work on a PR to improve the Java grammar we'd love contributions along those lines._  Examples of arbitrary class name  and property highlighting can be found in other grammars. (Wren, Ruby, etc...)  Being simpler than most grammars it should be a little bit easier to work with the Java grammar than some other more complex grammars, like JS.

FYI: We do not leave individual tickets for "improve grammar X" open, or else we'd have over 200 tickets... help would definitely be welcome here, but I am closing this as a duplication for #2500.  These type of improvements would be welcome on any of our grammars, not just Java.

**Closed by joshgoebel** 2022-08-29 15:55 UTC
Labels: language, bug, help welcome
