### ISSUE TITLE
(java) `.class` should not detect as keyword

### ISSUE THREAD

**Issue by taoalpha** [highlightjs/highlight.js#2428] opened 2020-02-25 20:44 UTC
**Describe the issue**
when have `class` key word and `=` in the arguments of a function, it will break the highlighting. A minimal code to reproduce this issue on 9.18.1 as follow:

```
public class T {
  public void a() {
    test( A.class, "a=b");
  }
  @Test
  public void b() {
    // ...
  }
}
```

while the code example works fine for 9.15.1.

9.18.1: http://jsfiddle.net/p9r1yd36/
9.15.1: http://jsfiddle.net/p9r1yd36/1/

**Expected behavior**
https://imgur.com/RTUfqny

**Actual behavior**
https://imgur.com/YU7ZDcj

**Comment by yyyc514** [comment] 2020-02-25 20:58
```
diff --git a/src/languages/java.js b/src/languages/java.js
index c70b99b0..9b73fb40 100644
--- a/src/languages/java.js
+++ b/src/languages/java.js
@@ -2,6 +2,7 @@
 Language: Java
 Author: Vsevolod Solovyov <vsevolod.solovyov@gmail.com>
 Category: common, enterprise
+Website: https://www.java.com/
 */

 function(hljs) {
```

Interesting... you may have found a parser regression of some kind.

**Comment by yyyc514** [comment] 2020-02-25 21:22
https://github.com/highlightjs/highlight.js/pull/2402/commits/e31cccdcff2505631008f990fbeaa0175b4a0f29

So weird.  Looks like sort of a poor mans fix to prevent keywords from triggering when following "." but a pretty hidden/strange way of going about it.  This only worked in the older parser because of how it had to run every regex test twice essentially ... so the parser would first see the match, then when it went back to examine it more closely to find out WHAT rule matched  it would fail to see it - and silently skip it.

The new parser does all this in a single pass... so we'll need a different fix.

**Comment by yyyc514** [comment] 2020-02-25 22:25
Curious: Is it common to overload the keyword `class` like this in Java?

**Comment by yyyc514** [comment] 2020-02-26 00:05
@taoalpha We're discussing this one.  If you're looking for a quick-fix and can build your own build from source the following patch would resolve the issue temporarily (just for Java):

```diff
diff --git a/src/languages/java.js b/src/languages/java.js
index f349a76a..7a08a36b 100644
--- a/src/languages/java.js
+++ b/src/languages/java.js
@@ -74,6 +74,7 @@ export default function(hljs) {
       hljs.C_BLOCK_COMMENT_MODE,
       hljs.APOS_STRING_MODE,
       hljs.QUOTE_STRING_MODE,
+      hljs.METHOD_GUARD,
       {
         className: 'class',
         beginKeywords: 'class interface', end: /[{;=]/, excludeEnd: true,
```

**Comment by egor-rogov** [comment] 2020-02-29 15:47
I'm wondering whether `class` in `.class` actually **should not** be detected as keyword?
I can't find an authoritative source, but in https://en.wikipedia.org/wiki/List_of_Java_keywords I see the following:

> The class keyword can also be used in the form Class.**class** to get a Class object without needing an instance of that class.

Meaning that `class` in `.class` **is** a keyword. So maybe it's not a parser bug, but simply a grammar bug?

Look how IntelliJ IDEA highlights the above example:

![test java](https://user-images.githubusercontent.com/12832436/75610611-d1cbd180-5b23-11ea-9919-de353f44e55b.png)

**Comment by yyyc514** [comment] 2020-02-29 16:12
I'd argue it's actually method dispatch there instead of a "language keyword", but a lot of that would depend on how the exact grammar is defining "keyword". I think with how Java uses keywords I'd vote no on this.  _I think you're getting too hung up on the exact wording..._ but you might be right.  I'm not certain of my stance.

If you are correct that simply means we'd need to add `class` into the global `keywords` and then the new behavior would kick in and it would be highlighted as a keyword, but not trigger the `beginKeywords`, which is what was causing the original issue.

@taoalpha You want to weigh in on this?

**Comment by yyyc514** [comment] 2020-02-29 16:14
> Look how IntelliJ IDEA highlights the above example:

I also wouldn't base our opinion solely on that or we'd have to go and change a lot of languages.  We often highlight a lot more or less than the "official" docs (or environment) for said language does - and you'd think if there was going to be any canonical "best" highlighting (for a given community) it would be with the project docs itself.

For an example see the currently open issue on Twig.

**Comment by egor-rogov** [comment] 2020-02-29 19:53
I'm not sure either. (And of course, that IntelliJ screenshot is no more than an example. I saw that GitHub doesn't highlight `.class` and wanted to see how other tools deal with it.)

I'm concerned with the special handling of an individual character (dot). Let's imagine there is a language with `class` keyword, and it allows to write, say, `A->class`. We'll need to get back to #2434 to add another exception? This makes me uneasy.

**Comment by yyyc514** [comment] 2020-02-29 20:20
> I'm concerned with the special handling of an individual character (dot). Let's imagine there is a language with class keyword, and it allows to write, say, A->class. We'll need to get back to #2434 to add another exception? This makes me uneasy.

_First off, lets be clear this was a legacy decision (that beginKeywords has magic `.` behavior)._  We broke it (unintentionally) with the new look-ahead enabled parser.  That PR tries to restore it doing as minimal damage at the same time as possible - ie, it does what it intended to do but it's less flawed than the original implementation.

I don't see another choice unless we're just going to say "that behavior was misguided, we're removing it on purpose now".  Which I suppose we could do, but I think that'd be the first intention large grammar change we've made.

> We'll need to get back to #2434 to add another exception? This makes me uneasy.

I don't think so.  I think the `.` is a one time exception (and a very common one, at that) and for such an example language the answer is: "add your own rule".  _OR enable more configurable keywords - as I suggest in the other open issue._ **I think that's the right long-term solution.**

In the future all of this will be possible with look-ahead and look-behind, so you can imagine doing it all with nothing more than the regex engine, but we're not there yet.

I'd say the reason this hasn't been spotted before now is that it's not super common for a language to use method names that shadow keywords - but it's possible in many languages (Ruby, JS, Java, just to name a few).

**Comment by yyyc514** [comment] 2020-02-29 20:21
So there the immediate question is what is the best short-term fix for this... adding `hljs.METHOD_GUARD` to a bunch of languages seems kind of crappy... do you have a proposal?

**Comment by egor-rogov** [comment] 2020-02-29 20:43
> First off, lets be clear this was a legacy decision (that beginKeywords has magic . behavior).

Ah, that was it. I had a feeling that I missed something important.
My proposal was to not treat dots specially and fix Java grammar instead. But as it was a legacy behaviour, we'd better restore it as you suggested. I'll take another look at #2434.

**Comment by yyyc514** [comment] 2020-02-29 20:58
> My proposal was to not treat dots specially and fix Java grammar instead.

Except it's not just Java, it's many grammars... and I kind of agree but just think we currently LACK the proper tools to "fix" them nicely. :-)

> we'd better restore it as you suggested.

When we have those tools at our disposal we can always revisit this and rip this hard coded behavior out.

**Closed** 2020-03-02 21:32 UTC
Labels: bug, parser
