### ISSUE TITLE
Request: Add support for styled-components

### ISSUE THREAD

**Issue by mxstbr** [highlightjs/highlight.js#1439] opened 2017-01-30 07:15 UTC
[`styled-components`](https://github.com/styled-components/styled-components) is a library for styling React applications that's fairly new (a few months old) and already quite widely used in the community.

A simplified example of its usage looks like this:

```JS
const Box = styled.div`
  color: palevioletred;
  background: papayawhip;

  @media screen and (max-width: 500px) {
    color: papayawhip;
    background: mediumseagreen;
  }

  &:hover,
  &:focus {
    color: red;
  }

  > h1 {
    color: palevioletred;
  }
`
```

As you can see, you can write actual CSS in JavaScript. The issue, as you can also see, is that there's no syntax highlighting, since there's no native support from syntax highlighters. (there's now support in Atom, Sublime and Vim, and other editors are being worked on)

It would be _awesome_ if `highlight.js` supported `styled-components`. I use `highlight.js` heavily on my website (and I know a lot of other people do too, thanks for making an awesome project!) and having `styled-components` support would be huge. In case you can see this as something worthwhile having let me know and I'll lay out the specifics of what's needed. (the API surface is a tiny bit bigger than just `styled.x`, but not much)

> In case you want to know about the benefits of this, admittedly slightly unusual, approach see [this article in SmashingMag](https://www.smashingmagazine.com/2017/01/styled-components-enforcing-best-practices-component-based-systems/) and [this talk from ReactiveConf](https://youtu.be/jaqDA7Btm3c). If you want to see a comparison with all other CSS in JS frameworks, see [this talk from ReactNL](http://www.youtube.com/watch?v=19gqsBc_Cx0). (note: this is where `styled-components` was released, its first mention happens at ~25 minutes. "One more thing...")

**Comment by kuworking** [comment] 2019-09-30 08:04
I can see that there is still no support for styled-components, or at least this is not working for me

![image](https://user-images.githubusercontent.com/4474004/65860027-b63c7f00-e369-11e9-90d4-03220106a7ad.png)

**Comment by yyyc514** [comment] 2019-10-07 07:21
I think for something like this the React community may have to contribute a React grammar much the same as we have the VueJS grammar for Vue.js.  I'm sure we'd be open to reviewing a PR for this, but long-term it might be better to split JSX out into it's own thing.  Grammars with their own maintainers (or group of maintainers) are going to be easier to keep up-to-date with the latest trends like this I think.

Ref: https://github.com/highlightjs/highlightjs-vue

@marcoscaceres Any thoughts on this one?

**Comment by yyyc514** [comment] 2019-11-21 16:24
Actually if this is just the ES6 custom string literal stuff then we definitely should support it in our Javascript language.

**Comment by yyyc514** [comment] 2019-11-21 16:30
> As you can see, you can write actual CSS in JavaScript.

Well, you can actually write anything in JS as long as it's enclosed in a string, which is all that is happening here.

Actually can you be 100% clear what you are requesting here?  We already highlight template literals as strings... so the first example you gave should work (and does in my testing).  _Of course the internal content is JUST a string_, it's not going to get magic highlighting as anything else (css, HTML, etc)...

That's not a part of Javascript, so wouldn't be something we'd add to the JS language highlighter.

The second example looks to be a known issue with our JSX support, and not related to styled components specifically (that I can see).

**Comment by yyyc514** [comment] 2019-11-21 16:33
Closing the original request as out of scope and the follow-up as a duplicate of https://github.com/highlightjs/highlight.js/issues/1915.

Example showing we do highlight string templates:

https://jsfiddle.net/ajoshguy/ocq8sad9/

**Closed by yyyc514** 2019-11-21 16:33 UTC
Labels: enhancement, help welcome, language

**Comment by yyyc514** [comment] 2019-12-14 15:16
Actually I just leaned we do highlight HTML and CSS if you use `html` or `css` as the prefix:

```js
  var HTML_TEMPLATE = {
    begin: 'html`', end: '',
    starts: {
      end: '`', returnEnd: false,
      contains: [
        hljs.BACKSLASH_ESCAPE,
        SUBST
      ],
      subLanguage: 'xml',
    }
  };
```
