### ISSUE TITLE
Not possible to download a package with all languages from the website

### ISSUE THREAD

**Issue by wojciech-kulik** [highlightjs/highlight.js#4031] opened 2024-04-03 13:18 UTC
https://highlightjs.org/download - if I select all languages (it also happens for some smaller undefined number of languages), the downloaded zip is always 139 bytes and it's broken.

**Comment by WhyFenceCode** [comment] 2024-04-03 18:47
I have the same issue, so i can verify that this is an issue. I talked to others and they have the same thing.

**Comment by WhyFenceCode** [comment] 2024-04-03 18:59
more info, i did some digging, and i found that it outputs 502 Bad Gateway when the request is sent.

**Comment by WhyFenceCode** [comment] 2024-04-03 19:10
it currently works with one lang at a time

**Comment by joshgoebel** [comment] 2024-04-04 04:30
Closing as duplicate of https://github.com/highlightjs/highlightjs.org/issues/15

**Closed by joshgoebel** 2024-04-04 04:30 UTC
Labels: bug, help welcome, parser
