### ISSUE TITLE
JSX highlighting issues when in string template literals

### ISSUE THREAD

**Issue by mattwelke** [highlightjs/highlight.js#1712] opened 2018-03-15 04:07 UTC
I'm having an issue with JSX. I am creating TSX files, but I notice there is a lack of support right now for TSX. I fell back to JSX, expecting to just lose the highlighting for constructs like `extends` and `implements` and the type annotations.

Instead, it appears that even with JSX set as the language, it stops highlighting half way through in some situations, like within string template literals:

![image](https://user-images.githubusercontent.com/7719209/37443781-9643f210-27e4-11e8-94d4-53a9f8c83e15.png)

Version: 9.12.0

**Comment by yyyc514** [comment] 2019-10-07 10:29
Close this as a duplicate of: 

https://github.com/highlightjs/highlight.js/issues/1915

**Closed by yyyc514** 2019-10-07 10:29 UTC
