### ISSUE TITLE
Make styles available at same path in npm package and repo

### ISSUE THREAD

**Issue by mk-pmb** [highlightjs/highlight.js#1898] opened 2018-10-31 23:51 UTC
Hi, thanks for highlight.js! I use it in [pre2gfmarkdown-pmb](https://github.com/mk-pmb/pre2gfmarkdown-pmb-js/) and it works great. However, currently [my demo](https://mk-pmb.github.io/pre2gfmarkdown-pmb-js/docs/demo/hello.html) needs two paths to the style sheets because in the repo they're in `src/styles/` while in the npm package they're in `styles/` (no `src/`).
Could you please add a symlink `src` —> `.` or a subdir `src` with symlink `styles` —> `../styles` to the npm package, so I can use just the `src/styles/` path and won't have to worry whether someone cloned or npm-installed the package?
Edit: Or for shorter URLs, add a symlink `styles` —> `src/styles` to the repo.

**Comment by mk-pmb** [comment] 2019-10-16 20:15
> Anyone using it should be using it in built form

1. Why? My demo seems to work.
1. In case there are people who do use raw form for whatever hacky workarounds they built, what benefit would you gain from making it *not* work with the npm version? Is there some kind of non-trivial cost in one additional directory with one additional symlink?

If there is, no problem; meanwhile I'm used to having git repos as my npm version spec, so if the npm package isn't helpful for my project, I could just ignore it and use the repo directly.

**Comment by yyyc514** [comment] 2019-10-17 00:21
> Why? My demo seems to work.

Does it really?  Because you seem to be saying 'it doesn't work without this symlink"... which is not the same as saying it works.

> In case there are people who do use raw form for whatever hacky workarounds they built, what benefit would you gain from making it not work with the npm version?

The repo is NOT the npm version.  They are different things.  They are purposely different.  The intention is that the source is in `src` and that it supports building. It's that way on purpose.  The repository is not a binary distribution.  If you would like a copy of the CDN build you can find it here:

https://github.com/highlightjs/cdn-release

**Comment by yyyc514** [comment] 2019-10-17 00:23
> I could just ignore it and use the repo directly.

The raw repo doesn't even include a built version of the javascript file...

**Comment by yyyc514** [comment] 2019-10-17 00:24
Closing as a non-issue.  The npm distribution and GitHub repository are not expected to match and are setup that way by design.

You can add a symlink manually if that works for you but I'd recommend using NPM (if that works) or building and actual usable super otherwise.

**Closed by yyyc514** 2019-10-17 00:24 UTC
Labels: npm/packaging/build

**Comment by mk-pmb** [comment] 2019-10-17 17:37
> Does it really? Because you seem to be saying 'it doesn't work without this symlink"... which is not the same as saying it works.

It does render my markdown, so at least those parts that matter to me, do work. It's just a bit ugly to need two separate style sheet links, but having two relative paths instead of one, is still prettier than having to specify one specific CDN as an external dependency.

> You can add a symlink manually if that works for you

That would require a build step on each update, which would void most of the plug & play "just works" magic I'm aiming for.

Nonetheless, highlight.js is a great project, so thank you for helping to maintain it.

**Comment by yyyc514** [comment] 2019-10-17 20:07
> It does render my markdown, so at least those parts that matter to me, do work. 

Interesting.  Which JS are you using?  While the source file might (currently!) work “as-is” the languages certainly do not.  And as we update our build process to use ES6 modules And newer stuff it’s also possible the source file won’t directly work anymore either - so that’s why we don’t recommend what you’re doing.

It’s a happy accident that it works at all, not intentional - and could break at any time.

**Comment by mk-pmb** [comment] 2019-10-17 20:24
I see now where we seem to have missed each other's point. My project has its own JS, baked together with HLjs by browserify. The only files it references directly from the HLjs repo are the color theme CSS.

**Comment by yyyc514** [comment] 2019-10-17 20:26
Yeah, you should probably honestly pull the CSS into your browserify/build process and move it where you prefer as part of your regular build process.  That’s how that is usually done I think. :)

So you’re using Browserify to build the JS?  Would you mind sharing your setup or at least the relevant parts?

**Comment by mk-pmb** [comment] 2019-10-17 22:28
It's shared already, under MIT license. [`build/rebuild.sh`](https://github.com/mk-pmb/pre2gfmarkdown-pmb-js/blob/master/build/rebuild.sh) It's gotten a bit old though, still uses uglify.

**Comment by yyyc514** [comment] 2019-10-18 00:33
Looks mostly greek to me. ;-)

**Comment by mk-pmb** [comment] 2026-07-07 16:31
For the archives, the symlink request was refused in #4197. Today it bit me again so I started my own fork that adds the `styles` symlink, see other thread.
