### ISSUE TITLE
(Lua) Insufficient highlighting

### ISSUE THREAD

**Issue by Stanzilla** [highlightjs/highlight.js#2624] opened 2020-07-01 16:31 UTC
**Describe the issue**

Currently Lua does not do highlighting very well at all, as an example:

![image](https://user-images.githubusercontent.com/75278/85955705-cb8a1c80-b980-11ea-92af-eb50be6486bb.png)

could at least look like this 

![image](https://user-images.githubusercontent.com/75278/85955749-23288800-b981-11ea-8068-fcd2e95dec6d.png)

**Which language seems to have the issue?**

Lua 

**Are you using `highlight` or `highlightAuto`?**

highlight
...

**Sample Code to Reproduce**

```
local targetData = ability:GetTargetData()
local wallPosition = targetData:GetHitPosition()
local playerDirection = targetData:GetAimDirection()
local conjuredWall = World.SpawnAsset(propIceWall, {position = wallPosition})
conjuredWall:LookAt(ability.owner:GetWorldPosition())
```

**Expected behavior**

**Additional context**

**Comment by yyyc514** [comment] 2020-07-02 13:22
This is by design.  In general we do not highlight variable definitions, function invokation, etc... but please see:

https://github.com/highlightjs/highlight.js/issues/2500

If you might be interested in helping us in this effort (as a Lua champion) please join the conversation over there. 

Closing (for now) as a dup of #2500.

**Closed by yyyc514** 2020-07-02 13:22 UTC
Labels: bug, help welcome, language
