### ISSUE TITLE
Suggestion: comparison with existing programming language detection tools

### ISSUE THREAD

**Issue by DonaldTsang** [highlightjs/highlight.js#2299] opened 2019-11-23 16:57 UTC
It seems that some have claimed that their project of predicting programming languages has a higher accuracy than HL.js, is it possible to take a look and see what makes it so special?
- https://github.com/andreasjansson/language-detection.el#model-performance
- https://github.com/github/linguist
- https://github.com/blakeembrey/node-language-detect
- https://github.com/ts95/lang-detector
- https://github.com/Prev/shaman

**Comment by yyyc514** [comment] 2019-11-23 18:14
> some have claimed

Obviously "some" doing some "claiming" is a pretty worthless standard. :-)  

Closing as a duplicate of https://github.com/highlightjs/highlight.js/issues/1213.  Feel free to drop your comments over on that thread though.  Thanks!

Surely worth taking a look into if anyone ever finds the time.  Auto-detection doesn't seem to be a super high priority though - though eventually I plan to swing back around to it.

**Closed by yyyc514** 2019-11-23 18:14 UTC
