### ISSUE TITLE
(protobuf) messages highlighting bug

### ISSUE THREAD

**Issue by Sannis** [highlightjs/highlight.js#1231] opened 2016-06-28 21:24 UTC
See #1229.

**Comment by yyyc514** [comment] 2019-10-07 01:56
I'm not familiar with the backstory on this and see the PR was merged.  Can you provide an example case of what the remaining issue seems to be?  Also a jsfiddle would be great.

Quick template:
https://jsfiddle.net/ajoshguy/nagkqytv/

And a confirmation this is still an issue today in 2019.

**Comment by yyyc514** [comment] 2019-10-13 19:12
Ping.

**Comment by yyyc514** [comment] 2019-10-16 15:06
Closing due to inactivity (we're cleaning out old stale issues that have likely been fixed).  If this is still a current reproducible issue please respond and we will happily re-open.

**Closed by yyyc514** 2019-10-16 15:06 UTC
Labels: needs reproduction
