### ISSUE TITLE
**SQL** - Missing key word: VARCHAR2

### ISSUE THREAD

**Issue by Marineone1** [highlightjs/highlight.js#2613] opened 2020-06-16 23:59 UTC
**Describe the issue**
Searching the key words, I could find VARCHAR, NVARCHAR and NVARCHAR2, but not the commonly-used key word **VARCHAR2.**

**Which language seems to have the issue?**
SQL

**Are you using `highlight` or `highlightAuto`?**
Neither. I looked at the key words themselves.

**Sample Code to Reproduce**
 ```
CREATE TABLE highlight (
  highlight_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  highlight_name  VARCHAR2(128) NOT NULL,
  highlight_descr VARCHAR2(500)); 
```

**Expected behavior**
VARCHAR2 key words highlighted.

**Comment by yyyc514** [comment] 2020-06-17 01:36
Which database is this?  We have many different grammars for different engines, SQL isn't meant to cover them all universally.

**Comment by Marineone1** [comment] 2020-06-17 21:49
Oracle Database

**Comment by yyyc514** [comment] 2020-06-20 04:19
I see no issue at all.  Please make 100% sure you are highlighting with SQL and SQL is built into the JS library you are using (it's not a default).  If so please provide a jsfiddle with a re-producable example.

![Screen Shot 2020-06-20 at 12 18 19 AM](https://user-images.githubusercontent.com/6473/85191089-90566200-b28b-11ea-8cbb-c02c3499d636.png)

**Comment by yyyc514** [comment] 2020-06-22 12:52
Ping.

**Comment by Marineone1** [comment] 2020-06-22 20:31
Thank you. I'm a DBA and am just learning development, so don't know how to create a jsfiddle. However, I will ask someone I work with.

**Comment by yyyc514** [comment] 2020-06-22 20:44
Don't miss my comment:

>  Please make 100% sure you are highlighting with "sql"( not auto-detect) and that SQL is built into the JS library you are using (it's not a default).

At this point there is an 90% chance you're just using the library incorrectly or that SQL is not a built-in language.

**Comment by Marineone1** [comment] 2020-06-22 21:46
Hi thanks,

I haven't used it at all. I looked up the keywords on the site. I found that NVARCHAR2, which is rarely used, is included, but VARCHAR2, which is very commonly used, is not. You'll make it possible to be used by tons more people - all the people working with Oracle - by adding one keyword: VARCHAR2.

Thanks,
Mike

**Comment by yyyc514** [comment] 2020-06-23 01:26
>  VARCHAR2, which is very commonly used, is not.

Except it is included and it works just fine (see my diagnostic snap).  I'd wager you're not setting up the library properly or you're installing the SQL grammar. Again, hard to say without seeing your exactly step or a fiddle that reproduces the problem.

**Comment by Marineone1** [comment] 2020-06-23 03:25
Oh, then I missed it. I searched for it on the keywords page with no luck. Sorry to waste your time.


Thanks,
Mike

**Comment by yyyc514** [comment] 2020-06-23 11:30
>  I searched for it on the keywords page with no luck. 

I'm not sure what you mean.

https://github.com/highlightjs/highlight.js/blob/master/src/languages/sql.js#L140

Closing this issue unless we have an isolated reproducible example of the problem.  Seems to be a local setup/configuration issue.

**Closed by yyyc514** 2020-06-23 11:31 UTC
Labels: bug, help welcome, language, needs reproduction

**Comment by Marineone1** [comment] 2020-06-23 19:58
Thanks for your help.






Michael Milligan OCP
Sr Database Engineer
680 West 10000 South
S Jordan, Utah 84109
Mbl:  (801) 390-2555
mmilligan@sphera.com<mailto:mmilligan@sphera.com>
<http://www.sphera.com>
[cid:image003.png@01D2E9E6.57AD22C0]<https://www.linkedin.com/company/sphera>  [cid:image004.png@01D2E9E6.57AD22C0] <https://twitter.com/spherasolutions>   [cid:image005.png@01D2E9E6.57AD22C0] <https://www.facebook.com/Sphera-Solutions-1770154213255830/>
OCP 12c DBA  ▪  OCP Advanced PL/SQL  ▪  OCE SQL Expert

**Comment by yyyc514** [comment] 2020-06-24 14:13
Glad to help.
