### ISSUE TITLE
C/C++ Weird hex values highlight in enum

### ISSUE THREAD

**Issue by phuclv90** [highlightjs/highlight.js#2921] opened 2020-12-16 16:53 UTC
**Describe the issue**

Only the first `0` is highlighted

**Which language seems to have the issue?**

C and C++

**Are you using `highlight` or `highlightAuto`?**

No idea. It's the default setting on StackOverflow

**Sample Code to Reproduce**
```
enum Chairs
{
  OldChair1 = 0x00001,
  OldChair2 = 0x00002, 
  OldChair3 = 0x00004,
  NewChair1 = 0x80001,
  NewChair2  // 0x8002
 };
```
as can be found in [this StackOverflow question](https://stackoverflow.com/questions/28416809/storing-bitmask-integer-and-enum-in-the-same-value-how)

![image](https://user-images.githubusercontent.com/9285512/102378611-976eea80-3ff8-11eb-895c-2bc56f43bb86.png)

**Expected behavior**

The whole hex number is highlighted

**Additional context**

**Comment by Hirse** [comment] 2020-12-16 18:10
Looking at the linked post, it seems that the code is detected as `protobuf`:
![image](https://user-images.githubusercontent.com/2564094/102388294-6a81ef80-3f86-11eb-8be0-f451b6973010.png)

When setting the language to `cpp`, it is highlighted correctly:
![image](https://user-images.githubusercontent.com/2564094/102388453-9d2be800-3f86-11eb-9f45-cd066b950a47.png)

---

@joshgoebel when trying the auto-detect on the `developer`-playground, the same snippet is considered `crystal`, which also leads to broken highlighting:
![image](https://user-images.githubusercontent.com/2564094/102388575-d06e7700-3f86-11eb-8e7c-2846f71391fb.png)

**Comment by joshgoebel** [comment] 2020-12-17 04:47
For thoughts on auto-detect:

- https://github.com/highlightjs/highlight.js/issues/1213 (larger discussion)
- https://github.com/highlightjs/highlight.js/issues/2910 (more recently)

This is either a mixture of a StackOverflow issue or a pure auto-detect issue, which is just par for the course with a small code snippet like this.  All the X = Y looks very much like a properties or protobuf file which is why this is being auto-detected as on SO.  As @Hirse mentions if you manually specify the language on SO it will be highlighted correctly.

Closing this as `cantfix`, since auto-correct is "best effort" and often wrong for small snippets.  This is a limitation, not a bug.  Anyone with brilliant ideas on how to make auto-detect more genius are always happy to chime in. :-)

I will split off the Crystal comment to a separate issue as crystal's relevance tuning is CRAZY off and should be fixed.

**Closed by joshgoebel** 2020-12-17 04:47 UTC
Labels: bug, help welcome, language
