### ISSUE TITLE
[Request] Support punctuation token

### ISSUE THREAD

**Issue by CN-traveler** [highlightjs/highlight.js#3709] opened 2023-02-05 01:16 UTC
**Is your request related to a specific problem you're having?**
- vscode
![image](https://user-images.githubusercontent.com/55753029/216796502-2cab116a-6ad7-4e9b-a4d4-7517f31e0495.png)
- prismjs
![image](https://user-images.githubusercontent.com/55753029/216796528-e396c9ec-3766-4bf8-b251-f4505ae83820.png)
- highlight
![image](https://user-images.githubusercontent.com/55753029/216796553-f3902c27-3e1a-40c4-8e8c-6fed5633622f.png)

**Comment by joshgoebel** [comment] 2023-02-05 02:00
Which punctuation tokens specifically are you referring to?

**Comment by joshgoebel** [comment] 2023-02-05 03:05
Gotcha.  Some languages already support this, btw.  Javascript does not.

Closing as a duplicate of #2500 (that tracks this effort more broadly).  We're open to this if someone is willing to do the work (and it's also clean and maintainable) - but for many grammars this can be a thorny challenge as without a FULL parser often symbols are too ambiguous... Just using JS/TS as an example... `/` can be division or the beginning of a regular expression,  `<` can be a less than or part of a type definition in TypeScript...

Figuring out which is which is often quite hard without a full parser.

**Closed by joshgoebel** 2023-02-05 03:05 UTC
Labels: enhancement, parser
