### ISSUE TITLE
Please add React/JSX language support

### ISSUE THREAD

**Issue by ashkan-ahmadi** [highlightjs/highlight.js#3117] opened 2021-04-08 23:13 UTC
**Is your request related to a specific problem you're having?**
A better way to highlight React/JSX codes. Right now some JSX elements aren't highlighted correctly even when I use the `code="jsx"` attribute on the `code` element. For example, comments (//) lines inside the React fragments aren't highlighted as comments but plain text.

**Comment by joshgoebel** [comment] 2021-04-08 23:22
TLDR; This is no trivial task and might even be impossible.  

Closing as a duplicate of https://github.com/highlightjs/highlight.js/issues/2998

**Closed by joshgoebel** 2021-04-08 23:22 UTC
Labels: enhancement

**Comment by joshgoebel** [comment] 2021-04-08 23:28
If someone wanted to work on a 3rd party plugin/grammar that includes a FULL JSX parser I'd be open to that discussion, but unless it was TINY and super simple it would never make it into core.
