### ISSUE TITLE
Highlighting not working

### ISSUE THREAD

**Issue by buttercrab** [highlightjs/highlight.js#2655] opened 2020-08-15 13:44 UTC
I was reading [the rust book](https://doc.rust-lang.org/book/), however the code was not highlighted.

OS: MacOS Big Sur public beta
Browser: Chrome(Maybe Chromium) (Not on Safari)

Screenshots in 5 themes ([rust programming book](https://doc.rust-lang.org/book/ch01-02-hello-world.html#writing-and-running-a-rust-program)):

|Light|Rust|Coal|Navy|Ayu|
|:-:|:-:|:-:|:-:|:-:|
|![image](https://user-images.githubusercontent.com/34997549/90234135-20fb8980-de5a-11ea-97fc-8ddc08154007.png)|![image](https://user-images.githubusercontent.com/34997549/90234156-2953c480-de5a-11ea-96ea-3a7f7e4e8424.png)|![image](https://user-images.githubusercontent.com/34997549/90234171-31136900-de5a-11ea-9be2-8d764e5c9ce8.png)|![image](https://user-images.githubusercontent.com/34997549/90234183-3670b380-de5a-11ea-8939-3ab336244ce3.png)|![image](https://user-images.githubusercontent.com/34997549/90234199-3ffa1b80-de5a-11ea-8897-1f7241ee3ac2.png)|

As you can see, the code highlighting isn't working. 
However, the computed color is different from black.

Screenshot:
![image](https://user-images.githubusercontent.com/34997549/90234409-99fae100-de5a-11ea-9476-1f4ca808ff11.png)
(`println!` keyword is computed to orange in lower right)

**Comment by joshgoebel** [comment] 2020-08-15 13:54
_Looks like it's highlighting properly to me if the CSS classes are being properly applied._  When I visit the website I see the highlighting without any issues.  Without a specific reproducible example (JSFiddle, etc.) at first glance this seems to be a problem with your browser or perhaps with the Rust website's CSS?

Are you saying it works on Safari? Your post isn't 100% clear on that.

**Comment by buttercrab** [comment] 2020-08-15 13:55
> Are you saying it works on Safari? Your post isn't 100% clear on that.

Yes. Is is working on Safari.

**Comment by joshgoebel** [comment] 2020-08-15 16:02
Sounds like a website or browser issue.  If you can make a JSFiddle that reproduces the problem outside of the Rust website environment I'd be happy to take a look at it.

You can fork mine if it helps:
https://jsfiddle.net/ajoshguy/2bmdswn6/

**Comment by buttercrab** [comment] 2020-08-16 06:23
JSFiddle works in my browser. It's weird...

**Comment by joshgoebel** [comment] 2020-08-17 16:39
Sounds like a website or beta WebKit glitch maybe?  Works fine in Safari here on Mohave when I visit the Rust website.

**Comment by joshgoebel** [comment] 2020-09-05 00:40
@buttercrab Do you have any additional info or can reproduce this on non-beta software?  If not I'm going to close this as not reproducible and an issue with the BETA.

**Comment by buttercrab** [comment] 2020-09-05 02:29
I think I found a solution. You should close the issue.

**Comment by joshgoebel** [comment] 2020-09-05 02:49
> I think I found a solution. 

Care to elaborate? :)

**Closed by joshgoebel** 2020-09-05 02:49 UTC
Labels: needs reproduction

**Comment by buttercrab** [comment] 2020-09-05 05:38
I downgraded to MacOS 10.15 so I wasn't able to verify the solution but **flapjackfritz** [commented](https://github.com/rust-lang/mdBook/issues/1301#issuecomment-682445935) the solution.
