### ISSUE TITLE
Regex look-ahead expressions do not work properly (begin)

### ISSUE THREAD

**Issue by jandamm** [highlightjs/highlight.js#1696] opened 2018-02-17 16:09 UTC
This issue is somewhat related to #1550 where I commented too. 
But I decided to give a better/clearer example how to reproduce the issue.

The problem is that grouped regexes are combined with into one regex using | (OR). After the match, it is not checked if the match really matches to the current group.

To reproduce this issue, you can use this parser and replace the swift.js one with it.

```js
module.exports = function(hljs) {
  const VAR1 = { 
    className: 'variant_1',
    begin: /\b[a-z][A-Za-z0-9]*\b(?!\()/g
  };
  const VAR2 = {
    className: 'variant_2',
    begin: /\b[a-z]/g
  };
  return { contains: [{
    begin: /[A-Za-z0-9]\./, end: /[\.|\,|\)|\n]/,
    contains: [VAR1, VAR2]
}]};}
```

Now you match this code:
```html
<pre><code class="language-swift">
  a.make)
  a.bake()
</code></pre>
```

And it will turn into this:
```html
<pre><code class="language-swift">
  a.<span class="hljs-variant_1">make</span>)
  a.<span class="hljs-variant_1">b</span>ake()
</code></pre>
```

But actually `m` matches variant_2.

If you remove `VAR2` from the `contains` array it works fine. (`make`)
Same goes if you remove `VAR1`. (`m`, `b`)

**Comment by Soaku** [comment] 2018-03-16 19:06
Same is for me

**Comment by yyyc514** [comment] 2019-09-11 00:13
```html
<pre><code class="language-swift">
  a.make)
  a.bake()
</code></pre>
```

Can you please clarify what you believe the correct output should be for this given the above rules and why?

**Comment by jandamm** [comment] 2019-09-11 06:29
Over a year later I'm not a 100% sure but it seems to me that it should be
``` html
  a.<span class="hljs-variant_2">b</span>ake()
```
instead of
``` html
  a.<span class="hljs-variant_1">b</span>ake()
```

**Comment by yyyc514** [comment] 2019-09-11 12:24
Is that because you think contains is a SEQUENCED list of matches that are REQUIRED?

**Comment by jandamm** [comment] 2019-09-11 12:48
That is because I think that I can give a REGEX with a `className` and if it is matched the `className` is applied instead of the `className` that does not match.

**Comment by yyyc514** [comment] 2019-09-11 13:31
Ah I see now.   You're right.

The problem is `/\b[a-z][A-Za-z0-9]*\b(?!\()/g`, in that the way the parser is written the negative look ahead doesn't have a chance to do its thing... so it will always pass - so variant 1 is chosen. I'm not 100% sure why it isn't being greedier though. (though I think I can guess)

The parser takes ALL the matches for a given mode and the (terminators) of those and then scans thru the text from one terminator to the next...  The problem isn't lookaheads don't generate any "output" so when the parser goes to analyze the match it only "sees":

- "make"
- "b"

And both those match the first rule.

**Comment by yyyc514** [comment] 2019-09-11 13:34
See my comment on #1349.  I suggested a way we could fix this. (I'm talking about positive look aheads, but it's all the same I think).

**Comment by yyyc514** [comment] 2019-10-19 21:10
If you test this against master you should find it now works.

**Comment by yyyc514** [comment] 2019-10-19 21:11
Closing as resolved and opening a new issue to track the `end` support.

**Closed by yyyc514** 2019-10-19 21:11 UTC
Labels: bug, parser
