### ISSUE TITLE
Including plaintext grammar in default distribution?

### ISSUE THREAD

**Issue by titpetric** [highlightjs/highlight.js#1702] opened 2018-02-28 15:22 UTC
In case a language isn't bundled on the page, explicitly setting `.language-go` for example, will not add the hljs class to the code block here. Similarly, if you would use `.language-text` (not `.text` or `.no-highlight` as in #700), the hljs class also isn't added to the code block.

The expected behaviour would be that any `.language-*` class will add the `.hljs` block, so the code block will get basic styling (padding, background color, text color).

**Comment by titpetric** [comment] 2018-02-28 15:32
Was also discussed in this PR: https://github.com/isagalaev/highlight.js/pull/430 (but wasn't implemented, from what I see).

**Comment by Pinjasaur** [comment] 2019-05-04 05:24
Hi @titpetric, I found this issue searching for a similar problem. It seems it was discussed in #1822 and fixed in #1834.

The tricky part I had a hard time figuring out was pairing the `class="plaintext"` with the `plaintext` language: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.6/languages/plaintext.min.js

After that, it worked as expected.

Pinging @egor-rogov & @marcoscaceres as you were both very active in the two issues/PRs linked above. Would like to see this clarified in the documentation or perhaps having the `plaintext` language shipped in the bundle by default?

The latter seems like a sane solution given the entire `plaintext` language is (minified) as:

```js
hljs.registerLanguage("plaintext",function(e){return{disableAutodetect:!0}});
```

**Comment by titpetric** [comment] 2019-05-04 07:07
+1 for both, whatever makes users life easier :)

**Comment by egor-rogov** [comment] 2019-05-13 09:11
Hello all,
I have no objections to bundle `plaintext`. @marcoscaceres what do you think?

**Comment by marcoscaceres** [comment] 2019-05-13 10:36
I've no objection either. It's straight forward enough to make custom package bundles, so if this helps, then sure.

**Comment by yyyc514** [comment] 2019-10-06 08:54
@marcoscaceres Think this is done now?

**Comment by Pinjasaur** [comment] 2019-10-08 04:54
Hey @marcoscaceres, I see this issue got closed but the problem is still present. The `plaintext` language is not bundled in the default 9.15.10 version (the latest as of this writing).

Here's a minimal demo on CodePen: https://codepen.io/Pinjasaur/pen/MWWYGoY?editors=0010

You can uncomment the `document.write` to show that explicitly adding the `plaintext` gives the expected behavior.

cc @yyyc514

**Comment by marcoscaceres** [comment] 2019-10-08 05:02
Apologies for the premature close. Thanks for providing the additional test case.

**Comment by yyyc514** [comment] 2019-10-09 06:16
@Pinjasaur Thanks for the catch.

That seems like a rather glaring omission.

@marcoscaceres @egor-rogov Any objections to adding `plaintext` to the defaults?  Where do we even configure the list of defaults for distribution, is that somewhere in the codebase?

Do I need to open an issue regarding how do we do releases?

**Comment by Pinjasaur** [comment] 2019-10-10 04:17
My quick $0.02: the primarily confusing part is `plaintext` is checked on https://highlightjs.org/download/ implying that it's bundled in the default distribution.

**Comment by yyyc514** [comment] 2019-10-10 11:23
Agree.

**Comment by yyyc514** [comment] 2019-10-10 14:51
@egor-rogov You added it.  Is there a reason the existing noHightlightRe wasn't sufficient and we needed a grammar?

**Comment by egor-rogov** [comment] 2019-10-10 14:56
Yes, there is.
`plain` (or something else from `noHighlightRe`) entirely skips processing of the block.
`plaintext` makes the block look like "code", i. e. applies CSS to it. It is intended to "highlight", say, output of SQL queries: no actual highlighting is needed, but output should be formatted like code.

**Comment by egor-rogov** [comment] 2019-10-10 18:13
Right, but you not always has direct access to styles, e. g. html can be generated by CMS etc.

**Comment by yyyc514** [comment] 2019-10-14 22:20
At the very least this will make it into the next common release:

https://github.com/highlightjs/highlight.js/pull/2204

So closing this issue. :-)

**Closed by yyyc514** 2019-10-14 22:20 UTC
Labels: cdn, npm/packaging/build
