### ISSUE TITLE
(C/C++) Hex float literal hilit

### ISSUE THREAD

**Issue by sprintersb** [highlightjs/highlight.js#4065] opened 2024-06-11 09:57 UTC
**Describe the issue**

The rendering of a hexadecimal floating-point constant may stop in the middle of the literal

```cpp
double a = -0x1.638e38e38e38ep5;
```
Live example: https://stackoverflow.com/q/78603151/1556746

Such literals are supported since C++17 / C99.

**Which language seems to have the issue?**

C/C++ (in stackoverflow what's renderd for the `cpp` "language").

**Are you using `highlight` or `highlightAuto`?**

Dunno. Using stackoverflow, and they said at Meta that I should report it here at highlight.js
...

**Sample Code to Reproduce**

```cpp
double a = -0x1.638e38e38e38ep5;
```
though the artifact looks different here than on stackoverflow.

**Expected behavior**

A literal should either be highlightet completey, or not at all.

**Additional context**

Popped up in the context of stackoverflow

**Comment by Dxuian** [comment] 2024-08-18 23:48
i believe i have a fix for this and i am going for a pr 
(new to open source pls be nice)

![before](https://github.com/user-attachments/assets/490850cb-244e-4b55-a503-6c269775d79d)
![after](https://github.com/user-attachments/assets/8fca8016-a352-4137-81cb-554eb6d9c750)

**Comment by Dxuian** [comment] 2024-08-18 23:56
i reproduced the error only in c and couldnt reproduce it in cpp 
so ive managed to come up with a fix for the problem in c and im going for a pr 
(first os commit please be nice 😀)
first image is before 2nd is after 
![before](https://github.com/user-attachments/assets/8bcd0d29-02b9-4f83-a627-934c80d0d36b)
![after](https://github.com/user-attachments/assets/e2f152e1-3890-4b4e-9acc-f2abd1cda2d9)

**Closed** 2024-08-25 21:58 UTC
Labels: language, bug, help welcome, good first issue
