### ISSUE TITLE
Escaping quotes in bash broken

### ISSUE THREAD

**Issue by mikesir87** [highlightjs/highlight.js#1930] opened 2018-12-20 21:26 UTC
When using escaped quotes in bash, the highlighting breaks. This applies to latest version (currently 9.13.1).

### Live Example
URL: https://plnkr.co/edit/u0diCW1oxmKhLOEwKo8W

### Example bash script
```
#!/bin/bash
DATA=$(curl json | cut -d\" -f4)
echo "$DATA"
```

### Sample Screenshot 

![screen shot 2018-12-20 at 4 25 27 pm](https://user-images.githubusercontent.com/746837/50311630-e1f21680-0473-11e9-90ff-8c396576b2ba.png)

**Comment by Inzeppelin** [comment] 2019-05-13 16:22
Is it worth hoping that this one will be fixed? Still reproducible in 9.15.6

**Comment by marcoscaceres** [comment] 2019-05-21 05:46
PR welcome 🙏

**Comment by Inzeppelin** [comment] 2019-05-27 10:23
@marcoscaceres Done! https://github.com/highlightjs/highlight.js/pull/2041
I suggest `/(?<!\\)"/` will do the trick

**Closed** 2019-05-27 10:53 UTC

**Comment by Inzeppelin** [comment] 2019-06-03 07:51
Just for history logs:

Finally, we specified escaped quote as independent syntax construction without any class name:

```javascript
var ESCAPED_QUOTE = {
    className: '',
    begin: /\\"/

  };
```

It has to work now since v9.15.8

**Comment by Inzeppelin** [comment] 2019-06-04 09:33
@marcoscaceres 

I found that it doesn't work with minified bundle

https://codepen.io/anon/pen/MdxXKg

Any suggestions?

**Comment by marcoscaceres** [comment] 2019-06-05 04:12
@Inzeppelin, sorry, I haven't re-released it yet. I'll try to gather a few fixes first and then release it as part of v9.15.9.

**Comment by marcoscaceres** [comment] 2019-07-31 03:21
@Inzeppelin, released v9.15.9... however, I'm unsure how long it takes for it to be uploaded to the CDN.

**Comment by Inzeppelin** [comment] 2019-08-06 19:56
It finally works! Tested in firefox as well. Here is working example: https://codepen.io/anon/pen/MdxXKg
Thank you!

**Comment by marcoscaceres** [comment] 2019-08-07 02:50
Glad to hear it. Sorry it took a bit long to release.
