### ISSUE TITLE
(CSharp) Function name highlight incorrectly

### ISSUE THREAD

**Issue by MaZhengKe** [highlightjs/highlight.js#3573] opened 2022-07-02 02:29 UTC
**Describe the issue**
Function name highlight incorrectly
![image](https://user-images.githubusercontent.com/30165889/176983126-01cde91c-80b5-4f10-9d65-6de3a6a8a48c.png)

**Which language seems to have the issue?**
CSharp / C#

**Are you using `highlight` or `highlightAuto`?**

use "highlight.js": "^11.5.1" with Node.js on the Server

**Sample Code to Reproduce**
```C#
    CoreUtils.SetRenderTarget(cmd, m_MirrorTexture, ClearFlag.All, Color.clear);

    var mirrorPos = MirrorPlanar.mirrorPos(MirrorPlanar.Plane,camTransform.position);
    var viewM = MirrorPlanar.GetViewMat(camTransform.position, rotation);
    var projectionMatrix = camera.projectionMatrix;
    projectionMatrix = GL.GetGPUProjectionMatrix(projectionMatrix, cameraData.IsCameraProjectionMatrixFlipped());
    
    cmd.SetGlobalVector(worldSpaceCameraPos,new Vector4(mirrorPos.x,mirrorPos.y,mirrorPos.z,0));
    RenderingUtils.SetViewAndProjectionMatrices(cmd, viewM, projectionMatrix, false);
```
**Expected behavior**

same code with C++ to highlight
![image](https://user-images.githubusercontent.com/30165889/176983339-b9bb5f1d-1a66-4790-baa5-a52480247d8c.png)

**Additional context**
I used the following code to test, C# and C++ gave completely different results
```JS
html = hljs.highlight('int a = CoreUtils.SetRenderTarget(Color.clear,10)', {language: 'c#'}).value
console.log(html)

html = hljs.highlight('int a = CoreUtils.SetRenderTarget(Color.clear,10)', {language: 'c++'}).value
console.log(html)
```
```html
<!--C#-->
<span class="hljs-built_in">int</span> a = CoreUtils.SetRenderTarget(Color.clear,<span class="hljs-number">10</span>)

<!--C++-->
<span class="hljs-type">int</span> a = CoreUtils.<span class="hljs-built_in">SetRenderTarget</span>(Color.clear,<span class="hljs-number">10</span>)
```

**Comment by joshgoebel** [comment] 2022-07-02 04:00
This is not a bug, it's a lack of a feature.  C# (and many other grammars) currently does not highlight property access or function dispatches.   A PR would always be welcome.  Closing as a duplicate of #2500 (catch all issue for desire for higher fidelity highlighting).

**Closed by joshgoebel** 2022-07-02 04:00 UTC
Labels: language, bug, help welcome
