### ISSUE TITLE
it doesn't  work well with 'ES6 & JSX' in some cases

### ISSUE THREAD

**Issue by Theoton** [highlightjs/highlight.js#1646] opened 2017-11-23 06:45 UTC
Just like the code: 

![01](https://user-images.githubusercontent.com/18453647/33161192-c0df0ee0-d05c-11e7-881b-35f654f15df2.png)
![02](https://user-images.githubusercontent.com/18453647/33161210-dca3affa-d05c-11e7-8e3f-1f399464786e.png)

**Comment by JeromeLin** [comment] 2018-10-17 08:39
+1, self-closing tags break JS(X) highlighting

**Comment by yyyc514** [comment] 2019-10-11 17:56
Yep... closing as duplicate of https://github.com/highlightjs/highlight.js/issues/1915

**Closed by yyyc514** 2019-10-11 17:56 UTC
