### ISSUE TITLE
install 9.15.2 fail

### ISSUE THREAD

**Issue by sbrunner** [highlightjs/highlight.js#1986] opened 2019-02-25 10:45 UTC
Same error as in #1984

**Comment by marcoscaceres** [comment] 2019-02-25 10:46
Muting, as duplicate of 
https://github.com/highlightjs/highlight.js/issues/1984

I'm posting updates there for folks that want to follow along. Nearly fixed!

**Closed** 2019-02-25 23:26 UTC
