### ISSUE TITLE
Problem with long XML file

### ISSUE THREAD

**Issue by lippomano** [highlightjs/highlight.js#2331] opened 2019-12-23 13:20 UTC
I need to highlight about 3000 lines of the XML file (it's a configuration file), but for some reason, it freezes and I can't do anything in my browser, someone else has this problem? is there a solution?

I am using Angular 8
browser chrome 79

**Comment by yyyc514** [comment] 2019-12-23 17:19
We'd really need an example of the file the reproduces the issue...

**Comment by yyyc514** [comment] 2019-12-23 17:20
Are you using the core library unmodified or any custom language files?

**Comment by yyyc514** [comment] 2019-12-24 16:49
Will auto close this in a few days if we don't have any reproducible examples.  You don't have to send your file necessarily - if you trim it down until you find what's causing the problem and then send us a small sample we can use to reproduce that'd be perfect!

We can always reopen anytime if a reproducible case is submitted. :-)

**Comment by lippomano** [comment] 2019-12-24 17:06
I am using [ngx-highlightjs](https://github.com/murhafsousli/ngx-highlightjs) but they told me to open this issue here.
here the example:
[link](https://drive.google.com/drive/folders/0B_she6Q8vsHrbDVMazN6cnM4WVU)

**Comment by yyyc514** [comment] 2019-12-24 17:11
Did you file an issue there?  Link?  `test.xml`?

<img width="409" alt="Screen Shot 2019-12-24 at 12 10 20 PM" src="https://user-images.githubusercontent.com/6473/71421039-61e22c00-2646-11ea-9e66-3f6df97a2b7a.png">

Tested in Safari and Chrome here, no issue.  I will test against 9.17.1 in one second just to confirm it's not something that's been fixed very recently.

**Comment by yyyc514** [comment] 2019-12-24 17:15
No issue with 9.17.1 either.  Looking very likely it's a problem with your setup or `njx-highlightjs`.

> browser chrome 79

What OS are you using and can you reproduce this on different computers/browsers, etc?

**Comment by yyyc514** [comment] 2019-12-24 17:17
Reference: https://github.com/MurhafSousli/ngx-highlightjs/issues/100

**Comment by yyyc514** [comment] 2019-12-24 17:45
@lippomano Or find out WHICH line of the file is the problem... Your file is 3081 lines.  

- Remove half of them?
- Does it still fail?
- Remove half of what's left?
- Does it still fail?

When you it starts working then add back what you removed and remove less... and eventually should be able to tell us:

"When I add these 3 lines, it fails, but without them it works just fine."

At that point we MIGHT be able to learn something even if we can't reproduce ourselves.

**Comment by yyyc514** [comment] 2020-01-01 18:33
Ping.  Going to close this soon if it's gone dead.

At this point we either need you to trim down the XML file and tell us exactly which tag/line is failing... or create a isolated test case we can independently verify.  Right now it sounds like it's something in your own personal setup or how you're using the code on your end.

I'd think it'd be easiest to trim down the file and try to isolate which PART of it causes the failure. That might help you solve it also even if it's not our issue.

**Comment by lippomano** [comment] 2020-01-02 12:02
I don't think it's just a part of the file.
Here you can see a video with about the first 600 lines of code, as you can see if I scroll with mouse wheel it still "freeze": [video](https://drive.google.com/open?id=1Qnn12L0qpap3sWvVOhc_Pe5E_UE_jbEM)

But in firefox, I can scroll normally so it's maybe related to chrome?

**Comment by yyyc514** [comment] 2020-01-02 13:21
> as you can see if I scroll with mouse wheel it still "freeze": video  But in firefox, I can scroll normally so it's maybe related to chrome?

This is a more helpful explanation I think.  I was imagining the browser HANGING permanently, not just pausing briefly.  

I'm going to close this as a duplicate of:
https://github.com/highlightjs/highlight.js/issues/2326

Chrome 79 has a lot of strange selection/scrolling issues for some people.  I don't think there is anything we can do here unless someone definitively can show us this is a HLJS issue and not just a Chrome issue.

**Closed by yyyc514** 2020-01-02 13:21 UTC
Labels: help welcome, needs reproduction
