### ISSUE TITLE
(VB.NET) Conditional Compiling Statements not highlighted correctly

### ISSUE THREAD

**Issue by pcr-coding** [highlightjs/highlight.js#2916] opened 2020-12-15 09:16 UTC
**Describe the issue**
When using conditional compiling, it gets formatted as comment.

**Which language seems to have the issue?**
This is an issue to VB.NET and also to VBA.

**Are you using `highlight` or `highlightAuto`?**
Using highlight (via tag associations on SO)

**Sample Code to Reproduce**
```vbnet
#Const conDebug = 1   ' Declare public compilation constant in Declarations section.

Sub SelectiveExecution()
    #If conDebug = 1 Then
        ' Run code with debugging statements.
    #Else
        ' Run normal code.
    #End If
End Sub
```
https://jsfiddle.net/pcrcoding/p6Lx3w09/

**Expected behavior**
It would be better looking something like below:
![image](https://user-images.githubusercontent.com/6593492/102194107-32fb4080-3ebd-11eb-8c99-b0bf67d0bd4a.png)
This is the highligting from Visual Studio Code.

**Comment by joshgoebel** [comment] 2020-12-15 13:53
Looks ok to me?

<img width="744" alt="Screen Shot 2020-12-15 at 8 53 25 AM" src="https://user-images.githubusercontent.com/6473/102223672-02aea480-3eb3-11eb-8f9d-f625f44b14b6.png">

**Comment by joshgoebel** [comment] 2020-12-15 13:55
There is a lot of VB.net work in 10.5 (pending) so I'm going to close this as already fixed in master.

**Closed by joshgoebel** 2020-12-15 13:55 UTC
Labels: bug, help welcome, language

**Comment by Hirse** [comment] 2020-12-16 21:59
Looking at the linked fiddle repro, this seems to be an issue with the Darcula theme, which colors comments and `meta` the same way:
![image](https://user-images.githubusercontent.com/2564094/102411564-f60b7880-3fa6-11eb-90b6-a1cfaa0d0e55.png)

**Comment by joshgoebel** [comment] 2020-12-17 04:29
@Hirse Well that would be an issue - but not a bug. :) Thanks for the additional eyeballs on this.
