### ISSUE TITLE
(C++) Cannot highlight std::map<std::string, std::string>

### ISSUE THREAD

**Issue by dctian** [highlightjs/highlight.js#3696] opened 2023-01-21 07:41 UTC
**Describe the issue**
Can not highlight generic types with two arguments, like `std::map<std::string, std::string>`

**Which language seems to have the issue?**
`C++`

**Are you using `highlight` or `highlightAuto`?**
`highlight`

**Sample Code to Reproduce**
Filename: `foo.cc`

This C++ code would print with syntax highlight.
```
std::vector<std::string> foo() {
};
```

This C++ code would NOT print with syntax highlight.
```
std::map<std::string, std::string> foo() {
};
```

Removing the 2nd argument from `std::map` would make it syntax highlight again.

```
std::map<std::string> foo() {
};
```

**Expected behavior**
See above.

**Additional context**
I am using highlight.js indirectly via vsc-print.  The original issue was reported here. https://github.com/PDConSec/vsc-print/issues/179#issue-1550616727

**Comment by PeterWone** [comment] 2023-01-21 10:48
Internally `vsc-print` is supplying a language identifier of `cpp` and I have verified the described behaviour. 
There seems to be a problem handling generics with two type parameters,

**Comment by joshgoebel** [comment] 2023-01-21 12:33
Is the pattern `<xxx::yyy` always guaranteed to be the beginning of a template, or might it possibly by a comparison expression?

**Comment by dctian** [comment] 2023-01-22 09:07
I am not a C++ compiler expert. But templates can take on many different forms...  

Here are some examples of templates.  But main idea is that the `<` would always have a matching `>` for template declarations.

```
// with namespace scopes
xxx::yyy<aaa::bbb>
xxx::yyy<aaa::bbb, ccc::ddd, eee::fff>

// without namespace scopes
yyy<aaa>
yyy<bbb, ccc::ddd, eee>

// or even nested templates
std::map<std::vector<int>, std::string>
```

For comparison expressions, the `<` less than operator don't need to have a matching `>`. But, in an contrived examples, it could look like the following:
```
// Check if the boolean of (a < b) is true
if ( a < b > 0) {
  ...
}
```

Hope this helps.  thanks!

**Comment by joshgoebel** [comment] 2023-01-22 16:41
<img width="443" alt="Screen Shot 2023-01-22 at 11 40 43 AM" src="https://user-images.githubusercontent.com/6473/213927704-b347b89c-70d8-42ba-a1df-939a9f2c861d.png">

Behavior seems consistent here in latest branch.

**Comment by joshgoebel** [comment] 2023-01-23 01:39
FYI: The new website will have this.

**Comment by joshgoebel** [comment] 2023-03-05 23:48
> Behavior seems consistent here in latest branch.

Ping.

**Comment by PeterWone** [comment] 2023-03-06 03:43
@joshgoebel I cannot test with v11 until you update @types/highlightjs, webpack5 could not digest it see #3722.

**Comment by joshgoebel** [comment] 2023-03-06 04:22
>  I cannot test with v11 until you update @types/highlightjs

We bundle our own types now, we do not use @types. 

Since I've confirmed that master does not have this issue I'm closing this issue for now.  

> webpack5 could not digest 

Happy to continue that discussion in the other issue.

**Closed by joshgoebel** 2023-03-06 04:22 UTC
Labels: language, bug, help welcome

**Comment by PeterWone** [comment] 2023-03-06 04:25
In that case I'll get rid of `@types/highlightjs` altogether and see what happens.
