### ISSUE TITLE
javascript arguments highlight

### ISSUE THREAD

**Issue by maor-benami** [highlightjs/highlight.js#3704] opened 2023-01-31 13:40 UTC
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/85426848/215775826-5ecedb7f-3c2e-4684-8f08-5dd4e5f464d9.png">

left image is web storm
right image is the web browser

can we get a separated `<span>` with a unique class name to make each argument different color?
and also, any other reference to arguments inside functions.
it make code so much readable

**Comment by joshgoebel** [comment] 2023-02-01 02:39
You mean the `x` inside the parens?

**Comment by maor-benami** [comment] 2023-02-01 03:39
> You mean the `x` inside the parens?

yes, both of them (orange/yellow text)

**Comment by maor-benami** [comment] 2023-02-01 03:43
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/85426848/215939932-34a0953c-5a14-4ea8-8f8a-7947a0e7294b.png">

I also see that in typescript there are "hljs-attr" elements, but they are in the wrong color.
is it also an issue with the github theme?

**Comment by joshgoebel** [comment] 2023-02-02 00:07
We have a `params` scope, but we've been slowly moving away from it since for many languages it's hard to pattern match on params (vs arguments) without a full parser - and instead just highlight function names/invokations since that's often an easier pattern, ie `call()`...

> is it also an issue with the github theme?

Possible.  GitHub is an entirely different engine so our theme should be thought of as "similar" not "exactly the same".

Here `t:` is highlighted as an object attribute though, not because it's a param... so yeah the color is going to be different.

**Comment by joshgoebel** [comment] 2023-03-05 23:47
Closing as asked-and-answered, expected behavior.  For better parsing of JS/TS we'd need a real parser, which would make the library *significantly* larger.  This tradeoff might not be a benefit for many of our users.

There are a few open issues regarding plugging other parsers into our highlighter if you had time and wanted to contribute to pushing that work forward. #3623 #3619

**Closed** 2023-03-05 23:47 UTC
Labels: language, bug, help welcome
