### ISSUE TITLE
Download from `highlightjs.org/download` fails if select all languages

### ISSUE THREAD

**Issue by RedCali** [highlightjs/highlight.js#4048] opened 2024-05-07 06:53 UTC
**Download from `highlightjs.org/download` fails if select all languages**

Selecting all languages will lead into an error during download on my browser (Edge and Chrome)
Browser consol shows error 502 - Bad Gateway

**Sample Code or Instructions to Reproduce**
- https://highlightjs.org/download
- check `Select all languages`
- click Download

Result in ZIP: [highlight.zip](https://github.com/highlightjs/highlight.js/files/15231510/highlight.zip)

![image](https://github.com/highlightjs/highlight.js/assets/36916361/f7ab92cd-9510-48cc-bb8d-ff43069a8cfd)

![image](https://github.com/highlightjs/highlight.js/assets/36916361/b4c55472-0689-4eb6-a402-41eb54e22fee)

![image](https://github.com/highlightjs/highlight.js/assets/36916361/bff772a5-5ee1-4af8-a2f7-87bba08b7f59)

**Comment by joshgoebel** [comment] 2024-05-08 02:37
Closing as a duplicate of https://github.com/highlightjs/highlightjs.org/issues/15.

**Closed by joshgoebel** 2024-05-08 02:37 UTC
Labels: bug, help welcome, parser
