### ISSUE TITLE
(python) Highlight problem with comments 

### ISSUE THREAD

**Issue by SalahAdDin** [highlightjs/highlight.js#1390] opened 2016-12-22 13:54 UTC
I'm using this library for highlight code in my site.

I test with a python code and i have this:
![problema](https://cloud.githubusercontent.com/assets/5034215/21427688/aff56978-c85e-11e6-9156-695780194aa3.png)

As you can see, the library takes all code lines after first comment like a comment, putting in gray the other code, without take in account that the other code lines aren't comments.

How can i solve this problem?

I saw that problem is with `#` symbol, when i delete comments with this symbol, all works:
![detectandoproblema](https://cloud.githubusercontent.com/assets/5034215/21427792/3d7fbbea-c85f-11e6-9f22-1c0cdce34672.png)

**Comment by o-jasper** [comment] 2018-05-19 13:34
Have same problem(highlight.js v9.12.0)

**Comment by yyyc514** [comment] 2019-10-07 04:03
In the past we've seen other libraries causing interactions that can result in breakage like this (Without it actually being a Highlight.js problem).  Can you reproduce this with a jsfiddle using the latest version of Highlight.js?  

A quick template:
https://jsfiddle.net/ajoshguy/nagkqytv/

Thanks,
Josh

**Comment by SalahAdDin** [comment] 2019-10-07 13:08
@o-jasper Can you?

**Comment by paladox** [comment] 2019-10-20 01:12
Isn't this the same issue as #1963? Which was fixed in #2214.

**Comment by yyyc514** [comment] 2019-10-22 18:24
@paladox No, the comments aren't inside the params here.  It's likely an issue with innerHTML and line breaks as mentioned.  

If there is still an issue please provide a jsfiddle that reproduces the issue apart from a larger environment and we'd be happy to look into it.  Or if you just need help sorting out the line break stuff we can probably help, but we're trying to close all the super old issues that don't seem to be issues anymore (no response).

Closing this due to inactivity.

**Closed by yyyc514** 2019-10-22 18:24 UTC
Labels: needs reproduction
