### ISSUE TITLE
(c-likes) Macro including single < breaks because it thinks it's a string

### ISSUE THREAD

**Issue by paladox** [highlightjs/highlight.js#1964] opened 2019-01-31 16:40 UTC
See https://chromium-review.googlesource.com/c/chromium/src/+/669484/4/ios/chrome/browser/ui/ui_util.mm and https://bugs.chromium.org/p/gerrit/issues/detail?id=7248

**Comment by yyyc514** [comment] 2019-10-07 01:51
I can't make any sense of this or these links.  If there is a bug with a specific language syntax please tell us which and if you could provide a jsfiddle reproducing the issue that'd be great:

Template you can use:
https://jsfiddle.net/ajoshguy/nagkqytv/

**Comment by paladox** [comment] 2019-10-20 00:18
@yyyc514 really sorry for the late reply.

If you do:

```cpp
#include "ios/chrome/browser/ui/ui_util.h"

#import <UIKit/UIKit.h>

#include "base/logging.h"
#import "ios/chrome/browser/ui/uikit_ui_util.h"
#include "ui/base/device_form_factor.h"
#include "ui/gfx/ios/uikit_util.h"

#if !defined(__has_feature) || !__has_feature(objc_arc)
#error "This file requires ARC support."
#endif

bool IsIPadIdiom() {
  return ui::GetDeviceFormFactor() == ui::DEVICE_FORM_FACTOR_TABLET;
}

const CGFloat kPortraitWidth[INTERFACE_IDIOM_COUNT] = {
    320,  // IPHONE_IDIOM
    768   // IPAD_IDIOM
};

bool IsHighResScreen() {
  return [[UIScreen mainScreen] scale] > 1.0;
}

bool IsPortrait() {
  UIInterfaceOrientation orient = GetInterfaceOrientation();
// If building with an SDK prior to iOS 8 don't worry about
// UIInterfaceOrientationUnknown because it wasn't defined.
#if !defined(__IPHONE_8_0) || __IPHONE_OS_VERSION_MAX_ALLOWED < __IPHONE_8_0
  return UIInterfaceOrientationIsPortrait(orient);
#else
  return UIInterfaceOrientationIsPortrait(orient) ||
         orient == UIInterfaceOrientationUnknown;
#endif  // SDK
}

bool IsLandscape() {
  return UIInterfaceOrientationIsLandscape(GetInterfaceOrientation());
}
```

For example, everything from "#if !defined(__IPHONE_8_0) || __IPHONE_OS_VERSION_MAX_ALLOWED < __IPHONE_8_0" and below is coloured in red (even IsLandscape() and any other function or what not after).

**Comment by yyyc514** [comment] 2019-10-20 00:48
Are you specifying the language?  If so which language?

**Comment by paladox** [comment] 2019-10-20 00:49
@yyyc514 It's objectivec.

**Comment by yyyc514** [comment] 2019-10-22 18:25
Can you make a fiddle that shows the issue?  I gave you a template above?

**Comment by paladox** [comment] 2019-10-22 19:35
@yyyc514 ah, sorry here's the fiddle: https://jsfiddle.net/8bvgu065/

**Comment by yyyc514** [comment] 2019-10-22 19:39
Thanks so much.  It's the `<`.  We likely think it's the start of a string and then can't ever find the end of the string, so comment goes on forever.

The grammar needs to be fixed to look-ahead and make sure there is actually an end > and if not to not consider it a string.  Also figuring out what is and isn't allowed inside a path string might help also... ie `#include <   some file>` probably isn't allowed... so just figuring out what is valid might be one quick fix for this.

**Comment by yyyc514** [comment] 2019-10-22 19:39
This probably has connections to the other C-like grammars also. (for someone wanting to work on a fix)

**Comment by davidben** [comment] 2019-11-10 17:12
Looks like this is specific to objectivec. The objectivec syntax definition is separate from the cpp one, with a much simpler preprocessor definition. https://github.com/highlightjs/highlight.js/pull/2265 syncs this part up.

**Closed** 2019-11-12 01:50 UTC
Labels: beginner friendly, help welcome, language
