### ISSUE TITLE
(JavaScript) It doesn't highlight properties or object methods

### ISSUE THREAD

**Issue by alvarotrigo** [highlightjs/highlight.js#3079] opened 2021-03-26 17:06 UTC
**Describe the issue**
JavaScript methos and properties are not highlighted correctly.

This is the result of applying JavaScript highlighting with hightlight.js 
![image](https://user-images.githubusercontent.com/1706326/112667398-7d497180-8e5d-11eb-809f-d8ec18921144.png)

Vs the one generated by GitHub ([source](https://gist.github.com/alvarotrigo/577bcdec5ba47cf615edd437f72c3a19))
![image](https://user-images.githubusercontent.com/1706326/112667507-9c480380-8e5d-11eb-803c-c5d4d851ef38.png)

It seems "off" in some way?

**Which language seems to have the issue?**
JavaScript

**Are you using `highlight` or `highlightAuto`?**
highlight
...

**Sample Code to Reproduce**
http://jsfiddle.net/x7vy30b6/

```html
<pre><code class="javascript">
//fadsfasfa
whatever.demo();
$.fn.whatever.demo.destroy();
</code></pre>
```

```js
$(document).ready(function() {
  $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
});
```

**Comment by joshgoebel** [comment] 2021-03-26 17:25
Thanks for your report!  This is indeed desirable behavior, but not the current behavior (for most languages).  See #2500 and #2521 for larger context of why this is complex.  If you think you could perhaps help out, feel free to join our Discord and lets talk.

There is currently a PR to add property support to Javascript if you wanted to test.  https://github.com/highlightjs/highlight.js/pull/3072/files

Closing as a duplicate of #2500.

**Closed by joshgoebel** 2021-03-26 17:25 UTC
Labels: bug, help welcome, language
