### ISSUE TITLE
(python) syntax highlighting bug

### ISSUE THREAD

**Issue by paladox** [highlightjs/highlight.js#1963] opened 2019-01-31 16:39 UTC
See https://chromium-review.googlesource.com/c/infra/infra/+/489582/10/infra/tools/dockerbuild/platform.py and https://bugs.chromium.org/p/gerrit/issues/detail?id=6652

**Comment by yyyc514** [comment] 2019-10-07 02:24
I can't make any sense of this or these links. If there is a bug with a specific language syntax please tell us which and if you could provide a jsfiddle reproducing the issue that'd be great:

Template you can use:
https://jsfiddle.net/ajoshguy/nagkqytv/

Is this a duplicate of https://github.com/highlightjs/highlight.js/issues/1964 ?

**Comment by yyyc514** [comment] 2019-10-13 14:07
I now understand that the site in question uses Highlight.js but we still really could use a much smaller reproducible example in something like jsfiddle.  We're very limited on time and the more direct information you provide the more likely an issue is to get addressed sooner rather than later.

Tagging this beginner friendly if a beginner wants to figure out the exact issue and create some smaller reproducible examples.

**Comment by paladox** [comment] 2019-10-15 19:52
For example doing something like:

```
class Platform(collections.namedtuple('Platform', (
    'name', # The name of the platform.
    'manylinux_name', # If the platform is "manylinux', the "manylinux" Docker
                      # image build name (e.g., "cp27-cp27mu").
    'wheel_abi', # The Python wheel ABI.
    'wheel_plat', # The Python wheel platform.
    'dockcross_base', # The "dockcross" base image (can be None).
    'dockcross_base_upstream', # Does the "dockcross" base image exist upstream?
                               # XXX: REMOVE once all do.
    'openssl_target', # The OpenSSL "Configure" script build target.
    'packaged', # Do Python wheels get packaged on PyPi for this platform?
    'cipd_platform', # The name of the CIPD platform to use.
    ))):
```

Causes everything to be blue. The comments are not highlighted (is plain black).

Then when it does:

```
# If the platform is "manylinux', the "manylinux" Docker
# image build name (e.g., "cp27-cp27mu").
```
It causes the second line to be blue and a mixture of blue on the first.

Also all text after cipd_platform is blue so e.g doing:

```
  @property
  def dockcross_base_image(self):
    if not self.dockcross_base:
      return None
    return 'dockcross/%s' % (self.dockcross_base,)
```

See screenshot: 
<img width="1438" alt="Screenshot 2019-10-15 at 20 52 10" src="https://user-images.githubusercontent.com/5727000/66864729-b35aa480-ef8d-11e9-9795-68f1d9bff75c.png">

**Comment by yyyc514** [comment] 2019-10-15 20:08
Looks like comments aren't detected inside function arguments... thanks for better examples. :-)

**Closed** 2019-10-18 23:52 UTC
Labels: beginner friendly, help welcome
