### ISSUE TITLE
sql - FOREIGN is not highlighted 

### ISSUE THREAD

**Issue by pleerock** [highlightjs/highlight.js#1563] opened 2017-07-05 11:22 UTC
It looks very weird that `FOREIGN` keyword in not highlighted, probably you should add it in the keyword list that needs to be highlighted in sql:

![sql](https://www.dropbox.com/s/xhhf5ro9msn5r1g/Screenshot%202017-07-05%2016.21.41.png?dl=1)

**Comment by DavidSimner** [comment] 2017-07-05 12:30
This is a duplicate of https://github.com/isagalaev/highlight.js/issues/1488

**Comment by DavidSimner** [comment] 2017-07-05 12:30
For Microsoft SQL Server's Transact-SQL (T-SQL), `foreign` is added as a keyword in https://github.com/isagalaev/highlight.js/pull/1524

**Comment by pleerock** [comment] 2017-07-05 12:39
I sent a PR for this fix. I hope this will be merged soon because its a very simple fix.
![sql](https://www.dropbox.com/s/cwh3zq4pztlvsq2/Screenshot%202017-07-05%2017.36.22.png?dl=1)

**Closed** 2018-09-02 01:47 UTC
