### ISSUE TITLE
(jsx) react code rendered improperly

### ISSUE THREAD

**Issue by greatbody** [highlightjs/highlight.js#1556] opened 2017-06-22 02:41 UTC
for such code:
```jsx
import React, { Component } from 'react';
import XX from 'xxx/XX;

export default class XXExample extends Component {
  render() {
    const options = [
      { text: 'xx', value: 1 },
      { text: 'xxx', value: 2 },
      { text: 'xxxx', value: 3 },
    ];

    return (
      <div style={{ margin: '20px' }}>
        <XX categoryOptions={options} />
      </div>
    );
  }
}

```

renders like this:

import React, { Component } from 'react';
import CategorySearch from 'uflight-ui/CategorySearch';

export default class CategorySearchExample extends Component {
  render() {
    const options = [
      { text: 'China', value: 1 },
      { text: 'UK', value: 2 },
      { text: 'USA', value: 3 },
    ];

    return (
       <div style={{ margin: '20px' }}>
      <CategorySearch categoryOptions={options} />  // notice this line is not aligned properly
     </div>
    );
  }
}

wonder if it is a bug?

thanks.

hljs:"version": "9.11.0"

**Comment by yyyc514** [comment] 2019-10-09 08:15
Does it solve itself if you replace the self-closing tag with a normal closing tag?

If so this is a duplicate and we already have an open issue for it.

Please confirm.

**Comment by yyyc514** [comment] 2019-10-16 15:08
Closing due to inactivity [and likely duplicate with the already tracked issue] (we're cleaning out old stale issues that have likely been fixed).  If this is still a current reproducible issue (that's not related to the end tag) please respond and we will happily re-open.

**Closed by yyyc514** 2019-10-16 15:08 UTC
