### ISSUE TITLE
What's the different between `highlightAuto()` and `highlightBlock()`

### ISSUE THREAD

**Issue by sky5454** [highlightjs/highlight.js#2629] opened 2020-07-07 05:08 UTC
I found `highlightBlock()` will add a attribute `class="hljs"` in order to bind highlight CSS, but `highlightAuto()` will not .

For I am using the `Web Worker`, so I can't use `highlightBlock()`  but only use `highlightAuto()` and add the code after hljs like this
```
element.classList.add("hljs");
```

The complete code is as follows
in index.html
```HTML
<script>
  addEventListener('load', () => {
  const code = document.querySelectorAll('pre code');
  for (let i=0; i<code.length; i++){
    const worker = new Worker('worker.js');
    worker.onmessage = (event) => {
        code[i].innerHTML = event.data;
        code[i].classList.add("hljs");
    }
    worker.postMessage(code[i].textContent);
  }
});
</script>
```

in worker.js
```JavaScript
onmessage = (event) => {
    importScripts('hljs10.js');
    const result = self.hljs.highlightAuto(event.data);
    postMessage(result.value);
 };
```

**Comment by yyyc514** [comment] 2020-07-08 17:33
Please see the API docs.

https://highlightjs.readthedocs.io/en/latest/api.html

This is the intended behavior.  `highlightBlock` highlights a DOM element - and would need to be run in the main web process.  `highlightAuto` returns a string.  If you are using workers then you are going to be responsible for updating the HTML yourself after you get the content back from the web worker.

**Comment by sky5454** [comment] 2020-07-09 04:26
> Please see the API docs.
> 
> https://highlightjs.readthedocs.io/en/latest/api.html
> 
> This is the intended behavior. `highlightBlock` highlights a DOM element - and would need to be run in the main web process to work. `highlightAuto` just returns a string - which you are responsible for doing something useful with. If you are using workers then you are going to be responsible for updating the HTML yourself after you get the content back from the web worker.

why not offer a func in Web Worke, like `highlightBlock` but has a String return valuer. I found the  `highlightBlock` and `highlightAuto` 's innerHTML has only one different in className `hljs` while others are same

**Comment by yyyc514** [comment] 2020-07-09 05:50
I am not sure what you are asking. Sorry.

**Comment by taufik-nurrohman** [comment] 2020-07-09 07:07
- `highlightBlock()` requires you to escape the HTML input in the block since you can preserve HTML elements in it such as `<a>` and `<mark>`.

 - `highlightAuto()` force you to keep the code input as is as it were a plan text object. It will then be escaped in the output before highlighted.

**Comment by yyyc514** [comment] 2020-07-09 11:25
> highlightBlock() requires you to escape the HTML input in the block since you can preserve HTML elements in it such as <a> and <mark>.

**No, HTML requires this escaping for security - to avoid code injection attacks.**  That has nothing to do with us.  `highlightBlock` is a DOM method, it is for convenience.  One could chose to simply NOT use it and instead use `highlightAuto` instead.  `highlightBlock` is a higher level API method - for the browser.

> highlightAuto() force you to keep the code input as-is as it were a plan text object.

Being a lower-level method, for use in or outside the browser, `highlightAuto` accepts plain text, yes.  I'm not sure what else it could possibly accept.

---

I am still not sure what they are asking exactly.

**Comment by yyyc514** [comment] 2020-07-09 11:28
> why not offer a func in Web Worker, like highlightBlock but has a String return valuer.

Our lower-level functions purposely to not render HTML, if you desire such behavior just add a wrapper yourself:

```ts
function highlightBlock(code) {
  let result = hljs.highlightAuto(code)
  let html = result.value
  return `<pre class="hljs #{result.language}"><code>#{html}</code></pre>`
} 
```
Web worker stuff is a more advanced usage of the library and if you're using it you should be willing to write some of the glue code to make it work with whatever application you're including it within.

**Comment by yyyc514** [comment] 2020-07-10 09:01
Closing as "working as expected".  The example code originally provided in the first issue is pretty much what I'd expect to see for a simple worker implementation - you are responsible for rendering the UI pieces yourself in the web process when using workers.

If someone was interested in tackling the "make workers easier to use" as a WHOLE complete task (which would touch lots of things), then I would be open to discussing that (though I also worry it would add unnecessary complexity), but not just tiny little one off changes.  Right now workers is a "complex use case" and as such requires some getting your hands dirty.

**Closed by yyyc514** 2020-07-10 09:01 UTC
