### ISSUE TITLE
Angular2 Code block's word wrap bug

### ISSUE THREAD

**Issue by skout90** [highlightjs/highlight.js#1584] opened 2017-08-06 15:51 UTC
![image](https://user-images.githubusercontent.com/11787240/28669324-ce5f56a2-730e-11e7-9115-48fb39f1a25a.png)

when my window width size is about 850px, code block become broken.
this code.
````html
<div>
  <input type="text" id="mainDiseaseCd" required [(ngModel)]="model.mainDiseaseCd">
</div>
````
 
look in my blog link at Step 4
https://skout90.github.io/2017/07/14/Angular/8.%20Angular%20%ED%8F%BC/

** It happend only chrome and safari. in Firefox, IE11 didnt happend**

**Comment by yyyc514** [comment] 2019-10-07 10:44
We would need a full reproducible case like a jsfiddle.

You can use my template here and fork it:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

Highlight.js doesn't do line numbers, so it might be that you're mixing it with some other software that is the source of your problems.

Closing because of age but if you can provide an isolated test case we can look at we'll be happy to reopen!

**Closed by yyyc514** 2019-10-07 10:44 UTC
Labels: needs_reproducable_sample
