### ISSUE TITLE
Highlightjs not respecting parent regex of a sub mode

### ISSUE THREAD

**Issue by algomaster99** [highlightjs/highlight.js#2238] opened 2019-10-30 05:24 UTC
I need to write a lexer which highlights my command-line tool commands properly.
```
$ dvc add file.csv
$ dvc pipeline list
```

So the command starts with `dvc` and it may have one or two subcommands - `add` or `pipeline list` respectively.

Therefore, it should highlight `dvc add` and `dvc pipeline list` in first and second case respectively.

```
contains: [
  {
    begin: /^\s*\$\s(dvc|git) [a-z-]+/,
    returnBegin: true,
    contains: [
      {
        begin: /dvc [a-z-]+ ?/,
        lexemes: '[a-z-]+',
        keywords: {
          built_in:
             'dvc'
          },
          contains: [
            {
              begin: /\w+(?![\S])/,
              keywords: {
                built_in: 'list'
              }
            }
          ],
          className: 'strong'
        }
      ]
    }
 ]
```

It matches `$ dvc pipeline list` even though the parent regex i.e. `/^\s*\$\s(dvc|git) [a-z-]+/` and should only match till `$ dvc pipeline`. How is it exactly functioning?

How does `/dvc [a-z-]+ ?/` override it and continues matching the expression?

**Comment by yyyc514** [comment] 2019-10-30 08:38
Please provide output HTML so it’s 100% clear what is happening. I find your description not that clear.

**Comment by yyyc514** [comment] 2019-10-30 08:47
Looks like your second begin matches **dvc pipeline** then your third grabs **list.**

**Comment by yyyc514** [comment] 2019-10-30 08:52
It’s all strong because your 3rd matches is a child of the 2nd.

**Comment by algomaster99** [comment] 2019-10-30 08:58
@yyyc514 but the parent regex - `/^\s*\$\s(dvc|git) [a-z-]+/` is not being respected if **dvc pipeline list** matches. How is this working exactly?

**Comment by yyyc514** [comment] 2019-10-30 09:00
I don’t think you understand how it works. The first regex matches then it starts looking for children. When matches **list**

**Comment by yyyc514** [comment] 2019-10-30 09:02
The regex only tells it to begin. It can keep matching if their are children to match.

**Comment by yyyc514** [comment] 2019-10-30 09:08
The parents BEGIN regex has nothing to do with children.

**Comment by algomaster99** [comment] 2019-10-30 10:05
@yyyc514 so how should I change my configuration to enable that? Basically, I would want to match `dvc pipeline list` but not `pics` in `dvc add pics` since 'pics' is not in `built_in`.
The current scenario makes both of them strong. Should I hardcode regex like this - `(?:list|...)`? (... Refers to list of all keywords I want to match)
Currently, both of the above commands become bold. And since, `dvc`, `pipeline` and `list` both are in `built_in`, they are colored blue too. `pics` doesn't get blue colored but it does get bold.

**Comment by yyyc514** [comment] 2019-10-30 12:13
Well depends how picky you want to be... You could probably get a long ways with just a single mode:

`$ (git|dvc) *` - then just FULL list of keywords

And then matching a long list of keywords... it wouldn't be "smart" but it might work for 95% of things...

Or you could go all the way the other way and have a single mode per subcommand:

```
"dvc add" (no keywords?)
"dvc something ..." (custom keywords for the ...)
"dvs pipeline ..." (custom keywords for the ...)
...
```

**Comment by algomaster99** [comment] 2019-10-30 12:27
@yyyc514 we were trying the second way only. But we don't know how to distinguish between `$ dvc pipeline <keyword>` and `$ dvc add <not-a-keyword>`.

**Comment by yyyc514** [comment] 2019-10-30 12:32
Well, that might be impossible in some circumstances.  But if you had a separate mode for each then you know how many keyword to expect, right?

Do for "dvc add" you'd be done... everything else should be arguments, no?  What are the keywords for add?

You only need to worry about matching keywords, not non-keywords.

**Comment by algomaster99** [comment] 2019-10-30 12:42
@yyyc514 dvc add doesn't have any. But "dvc pipeline" has one sub command called 'list'. So basically it can at most two sub-commands after 'dvc'

**Comment by yyyc514** [comment] 2019-10-30 12:43
Right... but again if you're doing "per subcommand" then it's be a tree...  Or you might do better just hard coding them all:

`(dvc add|dvc pipeline submit|dvc pipeline list|dvc ...)`

Or any combination. There are only like 20 ways to do the same thing here. :)

**Comment by algomaster99** [comment] 2019-10-30 12:53
@yyyc514 Yes, I want to do it "per subcommand". I just don't know how can I differentiate between `pics` in `$ dvc add pics` and `list` in `$ div pipeline list`. (`pics` is just a name of the directory.)

**Comment by yyyc514** [comment] 2019-10-30 12:55
Why would there be any problem?  per subcommand means writing outa  rule PER subcommand.

IE:

Rules:

- dvc add DONE
- dvd pipeline (subcommand keywords)

They would be ENTIRELy separate matchers.

**Comment by yyyc514** [comment] 2019-10-30 12:55
So if you had 20 commands you'd have 20 rules.

**Comment by algomaster99** [comment] 2019-10-30 12:57
@yyyc514 Okay you mean I make different sub-modes for commands with one sub-command and two sub-commands?

**Comment by yyyc514** [comment] 2019-10-30 12:59
Or a different sub-mode for EVERY command... really at this point you'd probably want to write code to build your syntax, not write it by hand...

```js
language_rules = []
add_command(language_rules, "dvc add", null)
add_command(language_rules, "dvc pipeline", keywords: {...})

return {
 contains: language_rules
}
```

**Comment by algomaster99** [comment] 2019-10-30 13:13
@yyyc514 I am sorry. But I am unfamiliar with this `add_command` function. I couldn't even find it here -https://highlightjs.readthedocs.io/en/latest/api.html

**Comment by yyyc514** [comment] 2019-10-30 13:24
It's an exercise for the reader, you'd have to write it yourself... I'm just talking about building the language dynamically using code.

**Comment by yyyc514** [comment] 2019-10-30 20:27
> what does immediately mean in this case?

It means immediately but if there are children/contains they will match. **If it worked the way you are thinking you could never have any children or subrules.** 

This may be a docs issues. Clarity could probably be added.

**Comment by yyyc514** [comment] 2019-10-30 20:28
> Then why did @algomaster99 had to put ? into /dvc [a-z-]+ ?/ to start matching dvc pipeline list? and just /dvc [a-z-]+/ didn't work as far as I understand.

I have no evidence right now this statement is true. The last bit eats the space which is often desirable.

**Comment by shcheklein** [comment] 2019-10-30 20:43
@yyyc514 `If it worked the way you are thinking you could never have any children or subrules.`

I though you can do `returnBegin: true` and then apply children rules if needed. And/or, specify `end` explicitly, e.g. `end: /\n|$/`.

**Comment by yyyc514** [comment] 2019-10-30 20:51
I think a big key is it’s always named “begin”. It BEGINS a mode, not ends it. When there are no more matches a mode ends. 

And again if you are expecting it to immediately terminate AND also including children your not thinking consistently. 

RetrurnBegin is a huge hack because we have no look behind.

**Comment by yyyc514** [comment] 2019-10-30 20:55
If you have a recommendation to update the docs a PR would be welcome. The behavior so far is correct as intended.

**Comment by shcheklein** [comment] 2019-10-30 21:10
> I think a big key is it’s always named “begin”. It BEGINS a mode, not ends it. When there are no more matches a mode ends.

totally, I'm not arguing with that. And again thank you for your help! 🙏 I'm just trying to fit in my head the way you describe it and what we actually see in our case.

For example this logic https://github.com/iterative/dvc.org/blob/master/src/Documentation/Markdown/lang/dvc.js#L47:L75 should be matching `dvc add` two times (twice the same kid) in this one:

```
$ dvc add dvc add
```

is it correct? Or am I still missing something? 

> returnBegin is a huge hack and often (always?) can be avoided with look ahead. It honestly should probably be deprecated.

As far as remember we had to use it this piece above to actually being able match at least one kid and apply different classes - `className: 'skipped'` for example. Again, may be we got it wrong but it works for us at `dvc.org/docs` very well (the current version, not the one @algomaster99 shared in this ticket.) Would really appreciate your feedback if you see any problem in that piece.

**Comment by yyyc514** [comment] 2019-10-30 21:15
> should be matching dvc add two times (twice the same kid) in this one:

At a glance, yes. Although you could use endsParent if that was undesirable. 

> As far as remember we had to use it this piece above to actually being able match at least one kid and apply different classes

Right. For look ahead. But real look ahead in regex actually work as of 9.16 so that’s a much better way.

**Comment by shcheklein** [comment] 2019-10-30 21:21
> At a glance, yes. Although you could use endsParent if that was undesirable.

That's not what happening for me. Thus I'm confused. It's very to reproduce in our project.

> But real look ahead in regex actually works as of 9.16 so that’s a much better way.

could you please elaborate, share a link?

**Comment by yyyc514** [comment] 2019-10-30 21:24
https://github.com/highlightjs/highlight.js/pull/2135

Looks at some of the smaller commits in this PR for examples.

**Comment by yyyc514** [comment] 2019-10-30 21:27
>That's not what happening for me. Thus I'm confused. It's very easy to reproduce in our project.

Make a jsfiddle and I’ll look at it.

**Comment by yyyc514** [comment] 2019-10-30 21:34
You could use end and excludeEnd to eat the space.

**Comment by shcheklein** [comment] 2019-10-30 21:40
> You don’t eat the space. So your rule DOES not match again because there is an extra space, which immediately ends the parent mode.

Yep, I see. That's right!

**Comment by shcheklein** [comment] 2019-10-30 21:52
> Looks at some of the smaller commits in this PR for examples.

thanks! I see that we can get rid of returnBegin this way indeed.

**Comment by yyyc514** [comment] 2019-10-30 22:29
Added:
https://github.com/highlightjs/highlight.js/pull/2242

Closing this as asked and answered, though conversation can continue if you have any other questions.

**Closed by yyyc514** 2019-10-30 22:29 UTC
