### ISSUE TITLE
(makefile) Syntax highlighting of Makefiles

### ISSUE THREAD

**Issue by TriMoon** [highlightjs/highlight.js#3878] opened 2023-10-03 18:25 UTC
**Describe the issue**
Syntax highlighting of Makefiles is bugged.

**Which language seems to have the issue?**
`lang-makefile`

**Are you using `highlight` or `highlightAuto`?**
no idea what Stackexchange uses...

**Sample Code to Reproduce**
- [demo](https://highlightjs.org/demo#lang=makefile&v=1&theme=atom-one-dark&code=IwlTUERYLUxpY2Vuc2UtSWRlbnRpZmllcjogQ0MtQlktTkMtU0EtNC4wCiMKU0hFTEwgPSAvdXNyL2Jpbi9iYXNoCi7FF0ZMQUdTID0gLWVjCi5PTkXFFToKLlNJTEVOVDoKClVUSUxTCQkJOj3JCys9IHNldGZhY2zME2Nob3duzhFtb2QKIyDLE25vbmV4aXN0aW5nCgokKGluZm8gIyMjIFNUQVJUOiBVdGlscyBjaGVjaykKIyBEZWZpbmUgbWFjcm8gd3J0IHNoZWxsLgppZmVxICjkAMUsJChmaW5kc3RyaW5nIMcS5QDDKSkpCnRvVXBwZXIJPSAkKMU7IMYpPSIkKMQKcCAkMSkiOyBwcmludGYgIiVzIiAkJHvGJV5efSkKZWxzZQojIEluc2lwcmVkIGJ5OiBodHRwczovL3N0YWNrb3ZlcmZsb3cuY29tL2EvMzc2NjA5MTYvMjI1MTAwNDLoAIQg6gCEZWNobyDtAIIgfCBzZWQgJ3MvLiovXFUmLycpCmVuZGlmxntwad97x3sxOTcyN8t7JChmb3JlYWNoIHV0aWwsxn4kKOUBjyksXAoJJChpZiDkAUJsdGVyLW915wFhLCQoxDEpxSTIJcY%2BY29tbWFuZCAtdiDHJSAyPiAvZGV2L251bGzGMgkkKGV2YWwgxQwJyDvGDgnqAWxcdDo9XHQlc1xuIsgdCSQoY2FsbCDnATXoAIkgKcsh%2FwCJ5wCJxjDGB8YGLCQoZXJyb3IgTm8gJ8c0JyBpbiBQQVRIxSPEBcQE5wKY9gCMKeUCTtccKSlcCuQCuVRoZXJlIGlzIGEgXHQgY2hhciBiZeQBjSB0aGUgPcR2xAnFZ2zkAuNhYm92ZSBmb3IgYWxpZ25tZW50Li4u7AMiRU5E7wMgxx0pICMgRW1wdHnFSgojIOgA6MUyRm9yY2VkKQo%3D)

```makefile
#	SPDX-License-Identifier: CC-BY-NC-SA-4.0
#
SHELL = /usr/bin/bash
.SHELLFLAGS = -ec
.ONESHELL:
.SILENT:

UTILS			:=
UTILS			+= setfacl
UTILS			+= chown
UTILS			+= chmod
# UTILS			+= nonexisting

$(info ### START: Utils check)
# Define macro wrt shell.
ifeq (bash,$(findstring bash,$(SHELL)))
toUpper	= $(shell string="$(strip $1)"; printf "%s" $${string^^})
else
# Insipred by: https://stackoverflow.com/a/37660916/22510042
toUpper = $(shell echo "$(strip $1)" | sed 's/.*/\U&/')
endif
# Inspired by: https://stackoverflow.com/a/37197276/22510042
$(foreach util,shell $(UTILS),\
	$(if $(filter-out shell,$(util)),\
		$(if $(shell command -v $(util) 2> /dev/null),\
			$(eval \
				$(shell \
					printf "%s\t:=\t%s\n" \
						$(call toUpper,$(util) ) \
						$(shell command -v $(util) 2> /dev/null)\
				)\
			)\
			,$(error No '$(util)' in PATH)\
		)\
	)\
	$(info $(call toUpper,$(util))	= $($(call toUpper,$(util))))\
)
# There is a \t char before the = in the info line above for alignment...
$(info ### END: Utils check)
$(info ) # Empty line
# $(error END: Forced)
```

**Expected behavior**

Something similar to how `kate` renders it, although that has some errors also... _(see the orange lines)_
![stackexchange](https://i.stack.imgur.com/G2BOn.png)

**Additional context**

See the Meta discussion: https://meta.stackexchange.com/q/393515/1288919

**Comment by joshgoebel** [comment] 2023-10-08 02:19
Well the "all green" after a certain point is likely a bug in how we handle strings, but if that sample is any indicator it looks like our handling of makefiles is pretty poor.  Would definitely be open to someone stepping up and improving things here.  The grammar is currently pretty simple and should be easier to build on than some.

**Comment by aneesh98** [comment] 2023-10-14 16:06
Hi Would like to work on this issue

**Comment by joshgoebel** [comment] 2023-10-15 04:44
Go for it. :)

**Comment by aneesh98** [comment] 2023-10-21 18:37
Hi while working on the fix for this issue, I noticed that the "dockerfile.js" present "src/languages" is being interpreted as a Dockerfile in VSCode (which I am using for development). Leading to incorrect syntax highlighting.
Check below screenshot for reference.
![image](https://github.com/highlightjs/highlight.js/assets/37235937/c3ab8991-0cf1-4d77-9b87-9382d215dd98)

I observed this also happens if I make files with any other extension (e.g. .py files for python). 
While this has got nothing to do with the highlight.js. I just wanted to open an issue in VSCode, and cite this file from the project as example where the issue occurs in VSCode. Hope that's fine?

**Comment by joshgoebel** [comment] 2023-10-21 21:34
All our code is open source, share it wherever... But I think one docker convention is that Dockerfile.* can be a dockerfile... so that might technically be correct in some sense, despite also being very wrong.  Curious what the VS Code people will say.

**Comment by aneesh98** [comment] 2023-10-22 09:03
HI @joshgoebel .
I have made the following change,
Currently the highlighting issue starts from the definition of toUpper macro within the ifeq statement:
```make
ifeq (bash,$(findstring bash,$(SHELL)))
toUpper	= $(shell string="$(strip $1)"; printf "%s" $${string^^})
```

I believe this is happening because the first string mentioned in the function call '"$(strip $1)"' is not being identified correctly and I think the cause is 'FUNC' variable in makefile.js doesn't currently include QUOTE_STRING

https://github.com/highlightjs/highlight.js/blob/17494c81dbade12834feedddf6fb208bcc9cbcce/src/languages/makefile.js#L32-L42

If I change the same to include QUOTE_STRING as done in my PR

https://github.com/aneesh98/highlight.js/blob/904ddd1295e48c1097795144b8bf21a533a8c6cf/src/languages/makefile.js#L32-L45

This is the obtained result.
![image](https://github.com/highlightjs/highlight.js/assets/37235937/c5009f65-08cc-4b7e-9d95-d179259ec3c6)

This does solve the initial formatting issue. 
But I observe few things here.
The string "$(strip $1)" is a function call is not being highlighted as per function call rules of Makefile but is being treated and highlighted as a plain string, as opposed to the screenshot posted under "expected behaviour" for this issue.

I am trying to fix this, but unable to understand on how I can proceed :sweat_smile: . Can you please help?
Another few things I observe is function "filter-out" has two formatting one before the hyphen and one after the hyphen could this be a RegExp issue?.

Kindly help. Thanks. :smile:

**Comment by joshgoebel** [comment] 2023-10-22 20:28
Keywords match in the order defined, so reverse the order of filter and filter-out.

If we're going to start including more things in $() then it's no longer only variables we're dealing with so we should remove that top-level scope...  perhaps add another rule to detect only SIMPLE variables like `$(name_here)`... 

I'm not sure exactly what the context of the code inside the `$() is though vs that outside.

**Comment by TriMoon** [comment] 2023-10-23 01:42
@aneesh98 
> But I observe few things here.
> The string "$(strip $1)" is a function call is not being highlighted as per function call rules of Makefile but is being highlighted as a plain string

Maybe that's because of:
https://github.com/highlightjs/highlight.js/blob/17494c81dbade12834feedddf6fb208bcc9cbcce/src/languages/makefile.js#L11-L12
https://github.com/highlightjs/highlight.js/blob/17494c81dbade12834feedddf6fb208bcc9cbcce/src/languages/makefile.js#L32-L33

hence the `className` needs to be different? :thinking: :wink:

**Comment by joshgoebel** [comment] 2023-10-23 01:55
Correct or blank, but I'm not familiar enough with Makefile to know what that content is...

**Comment by TriMoon** [comment] 2023-10-23 02:22
- `"$(strip $1)"` = The result is a string.
- `$(strip $1)` = Is a function call.
- `strip` = the function name.
- `$1` = the argument to the function.

**Comment by aneesh98** [comment] 2023-10-23 17:56
> Keywords match in the order defined, so reverse the order of filter and filter-out.
> 
> If we're going to start including more things in $() then it's no longer only variables we're dealing with so we should remove that top-level scope... perhaps add another rule to detect only SIMPLE variables like `$(name_here)`...
> 
> I'm not sure exactly what the context of the code inside the `$() is though vs that outside.

I understood for filter and filter-out, thanks for the explanation. I will make the change.
Little confused about what you said after that :sweat_smile: 

Is it regarding having function call and multiple arguments in `$()` like `$(foreach util,shell $(UTILS)`

What do you mean by top-level scope here?
>If we're going to start including more things in $() then it's no longer only variables we're dealing with so we should remove that top-level scope

**Comment by aneesh98** [comment] 2023-10-23 17:57
> @aneesh98
> 
> > But I observe few things here.
> > The string "$(strip $1)" is a function call is not being highlighted as per function call rules of Makefile but is being highlighted as a plain string
> 
> Maybe that's because of:
> 
> https://github.com/highlightjs/highlight.js/blob/17494c81dbade12834feedddf6fb208bcc9cbcce/src/languages/makefile.js#L11-L12
> 
> 
> https://github.com/highlightjs/highlight.js/blob/17494c81dbade12834feedddf6fb208bcc9cbcce/src/languages/makefile.js#L32-L33
> 
> > I am trying to fix this, but unable to understand on how I can proceed 😅 . Can you please help?
> 
> hence the value of `className` needs to be different? 🤔 😉 https://github.com/highlightjs/highlight.js/blob/main/docs/css-classes-reference.rst

Ahh yess. Guess the FUNC variable needs a class name change, will look into this. Thanks

**Comment by TriMoon** [comment] 2023-11-14 13:11
FYI:
> [!NOTE]
To assist you guys in improving the highlighting of makefiles:
[The latest version of the **main functionality** of this Makefile](https://gitlab.com/trimoon-inc/system/systemd-PPPoE/-/blob/main/CheckUtils.mk) is available in one-of-my repo's at GitLab. 😉🤝
_(Who knows maybe it will serve you also on occasions)_

**Closed** 2024-07-07 02:56 UTC
Labels: language, bug, help welcome, good first issue
