### ISSUE TITLE
(Bash and Shell) There is no syntax highlighting for the two. I've seen another issue but didn't seem it got answered.

### ISSUE THREAD

**Issue by dagweg** [highlightjs/highlight.js#4036] opened 2024-04-07 23:18 UTC
![image](https://github.com/highlightjs/highlight.js/assets/90281138/4f6b5227-a3b5-4a92-9f81-450155b73110)

The above is the one I'm trying to highlight using marked & I've correctly loaded the language 

`hljs.registerLanguage("bash", require("highlight.js/lib/languages/bash"));`

It doesn't highlight the code even though it works for all other languages.

**Comment by joshgoebel** [comment] 2024-04-08 00:42
Just registering a language doesn't highlight anything.  You'll need to be much more specific or provide an actual jdfiddle example.

**Comment by matanox** [comment] 2024-05-08 21:41
Don't most docs say that it does highlight the block?

**Comment by joshgoebel** [comment] 2024-05-12 02:39
<img width="436" alt="Screen Shot 2024-05-11 at 10 39 29 PM" src="https://github.com/highlightjs/highlight.js/assets/6473/1f0bbd61-3133-42af-bf17-b6a93d17122b">

Looks fine on the demo site.

**Comment by matanox** [comment] 2024-05-17 00:04
That's a bash script, looks good. I guess that for things like `python -m a.b.c --foo --bar 99` which I posted above, it does not actively apply highlighting, as can be seen above.

**Comment by joshgoebel** [comment] 2024-05-17 22:54
Yeah I think you're wanting a grammar we don't have.  Technically `--far` and `-m` and even numbers have no real special contextual meaning to the shell unless used in certain contexts (shell arithmetic, which we already support, etc).  And if we started highight non-built-in commands (like `python`) the list would have to be ridiculously long and would never be complete.

If someone made a strong argument for this as part of #2500 as an extension to Bash I'd listen - AND wanted to do the work, I'd listen, but otherwise I'm going to file this under "not a bug" and close the issue.

**Closed by joshgoebel** 2024-05-17 22:54 UTC
Labels: language, bug, help welcome

**Comment by matanox** [comment] 2024-05-18 19:16
Yes, you are right an all these assessments, I was wrong to call it bash syntax. 

It's probably helpful if a syntax for [python argparse](https://docs.python.org/3/library/argparse.html) syntax was defined, this syntax is not extremely complicated define: it's tokenized by spaces, keywords are prefixed with `-` or `--` and tokens not starting with these prefixes are just argument values. 

Maybe there are some more intricate cases to that de-facto grammar, but it can be a good start covering probably 80% of the cases, salvaging those long dull lines. What might be the turnaround time until any such "new" syntax definition makes it all the way to Github.com?

I'd take a try at it if it just boils down to defining a syntax and negotiating what its name would be. 

Thanks for your attention.

**Comment by joshgoebel** [comment] 2024-05-19 02:32
We have nothing to do with GitHub.  I'm not aware they use this library.

**Comment by RokeJulianLockhart** [comment] 2024-11-25 19:47
> https://github.com/highlightjs/highlight.js/issues/4036#issuecomment-2119069239

[`github.com/github-linguist/linguist/issues/new?template=new_language.md`](https://github.com/github-linguist/linguist/issues/new?assignees=&labels=Add+Language%2C+Good+First+Issue&projects=&template=new_language.md&title=) would be where to request this for GitHub itself.
