### ISSUE TITLE
(Python) Custom function name is highlighted only when it's declared

### ISSUE THREAD

**Issue by Choi-Sung-Hoon** [highlightjs/highlight.js#3495] opened 2022-02-26 14:18 UTC
**Describe the issue**
![image](https://user-images.githubusercontent.com/33472400/155846242-ea52de3d-0dda-41c5-b73a-ab21df5c9d9b.png)

I used `github-dark` theme.

It highlights the custom function, named `dfs` only when it's declared and it doesn't highlight when it's called.

**Which language seems to have the issue?**
Python, used `auto-detection`

**Are you using `highlight` or `highlightAuto`?**
highlightAuto
...

**Sample Code to Reproduce**

```python
import sys
 
dwarf_list = [int(sys.stdin.readline()) for _ in range(9)]
dwarf_check = [0 for _ in range(9)]
answer = []
 
 
def dfs(n, count, sum_height):
	if n == 9:
		if count == 7 and sum_height == 100:
			for idx, v in enumerate(dwarf_check):
				if v:
					answer.append(dwarf_list[idx])
			
			print(*sorted(answer), sep='\n')
			sys.exit(0)
		return
 
	# select a dwarf
	dwarf_check[n] = 1
	dfs(n + 1, count + 1, sum_height + dwarf_list[n])
	
	# don't select a dwarf
	dwarf_check[n] = 0
	dfs(n + 1, count, sum_height)
 
 
dfs(0, 0, 0)
```

**Expected behavior**
The custom function name `dfs` should be highlighted properly.

I think we should detect function names with proper regex.

**Additional context**
None.

**Comment by joshgoebel** [comment] 2022-02-26 15:16
Re: bug. This is the correct and expected behavior. We're just pattern matching the definitions. There is nothing special about the custom function name at the call site that would result in its highlight. 

Now if one wanted to add property access and function dispatch highlighting to Python (like we have added to some other languages recently) that would be a welcome PR.  That would make this a dupe under the whole overarching #2500 issue.

**Comment by joshgoebel** [comment] 2022-02-26 20:34
Closing as a duplicate of #2500.

**Closed by joshgoebel** 2022-02-26 20:34 UTC
Labels: language, bug, help welcome
