### ISSUE TITLE
Mixed languages style

### ISSUE THREAD

**Issue by 1-0** [highlightjs/highlight.js#3245] opened 2021-06-16 11:06 UTC
Is it possible to add mixed languages style?
(for example - mixing ruby, http, html)
![Screenshot_7](https://user-images.githubusercontent.com/762649/122208366-e0223600-ceab-11eb-97b7-24017bacbe1a.png)

**Comment by joshgoebel** [comment] 2021-06-16 14:42
Ok that's Ruby. But how would we have any idea what's inside the strings?

**Comment by taufik-nurrohman** [comment] 2021-06-16 16:37
If HTML-merging is not deprecated, I would think a solution like nesting the code container tags:

~~~ .html
<code class="hljs language-json">{
    "title": "<span class="hljs language-php">&lt;?= $title; &gt;</span>"
}</code>
~~~

**Comment by joshgoebel** [comment] 2021-06-16 16:41
I don't think auto-merged _ever_ handled cases like that... if I understand you properly you'd need to highlight individual spans "from the inside out" with `highlightElement` or something for that to work.

**Comment by taufik-nurrohman** [comment] 2021-06-17 02:47
> You could probably (carefully) build something like that on top of auto-merging, but it'd likely require some looping, recursion, etc...

Yes. I mean to use the auto-merging plugin as dependency.

**Comment by 1-0** [comment] 2021-06-17 06:49
"Explicit is better than implicit."
( https://www.python.org/dev/peps/pep-0020/ ;-) )
In my point of view - the better way to allow in highlight.js multiple tags use,
for example
<code class="my_some_laguage1">print("Hello from my_some_laguage1 !")</code>
<code class="my_some_laguage2">( princ "Hello from my_some_laguage2 !")</class>

**Comment by joshgoebel** [comment] 2021-06-17 16:02
Actually this is quite complex and I can't think of a trivial way to do it.  You can't just do it "inside out" because later highlighting phases would rehilighting the inner sections with the wrong language... there is no way to say "already highlighted".  With a custom grammar you can do this slightly with `sublanguage` (since now the parser itself is aware of what's going on)... say if you wanted a `ruby_where_strings_are_html` grammar... but doing this generically would almost require a custom parser or very ingenious glue around what already exists.

**Comment by 1-0** [comment] 2021-06-18 07:20
Let me try in "vanilla"
```var s = document.getElementByClassName('thing')`;`
And simply apply a new cascade style.

**Comment by joshgoebel** [comment] 2021-06-18 14:51
> `<code class="my_some_laguage1">print("Hello from my_some_laguage1 !")</code>`
> `<code class="my_some_laguage2">( princ "Hello from my_some_laguage2 !")</code>`

That's two different blocks, that's easy... and works already... what the original request was talking about is one language randomly nested inside of another, which is a much harder problem.

**Comment by 1-0** [comment] 2021-06-18 17:48
How are we are handle this (from me - old computer science teacher)? 
 I'll try to make some algorithm (we can do it by our self - no need ML) 
 I look at code at issue start:
 `res =` - res is is equal to 
 hmm - it must be a some pointer or some variable (in ruby - it is)
The quotation mark `"` opens 
It must be a start string (it is)
What is inside the string?
`Content-type:`
hmm - it must be a start of http response (it is)
what value of `Content-type`?
`text/html`
2 end of row in the end
The  quotation mark `"` is closing  - end of string
end of part of http response
`res = res +`
hmm - it must be appending to string
to http response (it is)
The quotation mark `"` opens 
It must be a start string
'<` - it must be a start of *(x)ml tag (it is)
'DOCTYPE` - hmm - it  must be a tag "DOCTYPE" (it is)
This is a html (it si)
`html` - tag has an attribute "html"
`>` end of tag "DOCTYPE" 
`<html>` - opened tag html
`<h1>`
`Hello from ruby!`
`</h1>`
`</html>`
`"` - end of string, end of html
empty string - end of some logic
`puts res` - calling method "puts" with argument "res"

Voila
I must to apologize - I'm a little tired 
As teach to me my teachers (students of grate Lev Landau):
I have not prepared myself, so I will speak for a long time

**Comment by joshgoebel** [comment] 2021-06-18 18:10
I didn't follow most of that (or try to) - probably due to formatting issues.

As I said the problem is not doing this _specifically_ - it's doing it in a general way that works with out existing framework and is flexible - without having to write custom logic.  And I don't think that's easily doable (outside of writing a grammar, which I've already mentioned).

My very first question is still highly relevant I feel:

> **Ok that's Ruby. But how would we have any idea what's inside the strings?**

**Comment by 1-0** [comment] 2021-06-18 18:25
I do not know 
maybe we always try to parse string content as code?

**Comment by joshgoebel** [comment] 2021-06-18 18:58
Except most strings are just strings, not code.

**Comment by 1-0** [comment] 2021-06-18 19:08
Ce la vie
If we can not parse this - just do not parse this

**Comment by joshgoebel** [comment] 2021-06-18 19:23
You say that as if it's easy to determine whether a string is taxed or something else. That's actually a really hard problem. Just because a string might have an HTML tag in it does not mean that it's HTML, etc.

**Comment by 1-0** [comment] 2021-06-18 19:39
I do not agree with you.
For us - for a person
this is a really very simple problem
Just try to handle this
how do you explain it to yourself

Try to use all known code languages

**Comment by joshgoebel** [comment] 2021-06-18 21:15
> For us - for a humans...this is a really very simple problem

So many things are... 😭🤷🏻‍♂️

>  Try to use all known code languages

Problem: False positives. 

Also, it might not be any language - even if it looks like it is.  I think code within strings in code is likely the edge case (out of all strings in the entire world).  So the majority of the time you'd just get false positives.  Perhaps your use case is different.

Not to mention it's not even trivial to know where the string ends once you start embedding other code:

```
var a = "test # "thingy""
```

- Is this plain text?  
- Is it ruby with a comment of `"thingy"`.. 
- how do we know if the `"` that starts thingy the end of the string or just content inside of a comment.
  - ...if you escape the string properly (for JS) you have a whole other host of problems:

```
var a = "x = \"thingy\""
```

Now it's valid Javascript and the string would be `x = "thingy"` (as seen by JS) - **but our parser can't easily know that - if does not decode JS encoded strings in source**  The content [as seen by the parser] (inside the quotes) is `x = \"thingy\"`... which isn't valid Ruby at all.  You'd have to first decode any escape sequences as JS before you could even being to understand what's inside the string.

_And now you're entirely outside the scope of what Highlight.js does._

---

If anything here has been helpful for you great.... if you've solved this problem and have some actual code to show us your solution, great... I'd certainly love to see a simple solution to what I know as very complex problem.  But I think you're just imagining the very simple cases... 

I'll point you to where we do something like this:

-  https://github.com/highlightjs/highlight.js/blob/main/src/languages/javascript.js#L103-L128

It works in this case because the strings are tagged... but even that could have subtle issues around escaping if it were mixed right in the middle of highlighted tokens in the sublanguage... such as having a `char.escape` right in the middle of a `variable` name...  very strange, but entirely possible.

**Comment by joshgoebel** [comment] 2021-06-18 21:17
I'l leave this open a bit longer incase you want to share an actual implementation (if you've actually solved this in some sort of elegant and general way). Otherwise tagging as "autoclose" since this has been answered to the best of our ability.

**Comment by 1-0** [comment] 2021-06-19 02:48
We shouldn't try not to try. We must stop this in time. We couldn't say. There is no recursion here. And different types of quotes, brackets, less signs, opening tags will tell us where what begins

**Closed** 2021-06-22 05:37 UTC
Labels: autoclose, enhancement, parser
