### ISSUE TITLE
NpmJs Registy packege is broken

### ISSUE THREAD

**Issue by DeadcatDev** [highlightjs/highlight.js#1989] opened 2019-02-25 14:29 UTC
Repository 9.13.1 and probably other repos being changed and **broke npm install** because of lacking some dirs/files alike tools as shown:

NMPJs Registry 9.13.1 version vs GitHub  9.13.1 release version:

![image](https://user-images.githubusercontent.com/15237149/53344371-d4915680-3912-11e9-91ca-8b62cd0a4325.png)

which is causing:
![image](https://user-images.githubusercontent.com/15237149/53344164-52089700-3912-11e9-810c-34a3ce281e8d.png)

**Comment by edclement** [comment] 2019-02-25 14:32
duplicate of #1984 #1986.

**Comment by marcoscaceres** [comment] 2019-02-25 14:38
It’s quite odd that the package itself is missing these folders. We don’t have an .npmignore file, so I’m still at a loss about why this happened.

**Comment by marcoscaceres** [comment] 2019-02-25 14:39
Closing as duplicate.

**Closed by marcoscaceres** 2019-02-25 14:39 UTC
