### ISSUE TITLE
Pre-compiled files?

### ISSUE THREAD

**Issue by idleberg** [highlightjs/highlight.js#678] opened 2014-12-15 11:42 UTC
I guess I'm not the only one looking for a way to get a pre-compiled files of hljs. So far, I tried several ways to overcome this, but none of the following was completely satisfying.
## Bower

Bower is probably where pre-compiled files would fit best, but the package available is _not official_ and _outdated_ (as you are aware). 
## npm

The package distributed on npm is made for — and that's fine, I guess, since this is what npm is primarily made for. As I understand it I cannot use the node package to embed it on a website. So, instead I tried to build it using Gulp. Since it's possible to specify any GitHub repository (if it comes with a `package.json`) as a dependency, I tried building hljs using node.

``` json
"devDependencies": {
  "highlight.js":   "isagalaev/highlight.js"
},
 "scripts": {
  "postinstall": "node node_modules/highlight.js/tools/build.js :common"
}
```

Unfortunately, this does not seem to work due to a problem with file permissions (I wonder if including an empty `build` folder would solve this). Next I tried [gulp-shell](https://www.npmjs.com/package/gulp-shell) to build directly from gulp, but the tasks aborts due to missing dependencies (of hljs).
## cdnjs

Ultimately, I ended up using a Gulp task that downloads JS and CSS from cdnjs. It works, but it left me with a somewhat _awkward_ feeling.

Is their another possibility I'm overlooking? Are there any plans to make this easier in the future? I suspect many users would welcome the idea to get pre-compiled files and Bower is _maybe_ the right place for it. Just my two cents.

**Comment by isagalaev** [comment] 2015-02-03 20:55
Getting back to this…

@idleberg yes, I think there's no harm in including a package.json in CDN builds. Could you make a pull request adding that to the build tool? The CDN-related build module is in tools/cdn.js, and may be you could reuse the package.json that we build for npm: https://github.com/isagalaev/highlight.js/blob/master/tools/node.js#L115

**Comment by kilianc** [comment] 2015-05-30 01:41
```js
gulp.task('hjs', function (done) {
  var opts = {
    cwd: __dirname + '/node_modules/highlight.js'
  }

  var npmInstall = spawn('npm', ['install'], opts)
  npmInstall.stdout.pipe(process.stdout)
  npmInstall.stderr.pipe(process.stderr)

  npmInstall.on('close', function (code) {
    if (0 !== code) throw new Error('npm install exited with ' + code)

    var build = spawn('node', ['tools/build.js', '-n', 'json'], opts)
    build.stdout.pipe(process.stdout)
    build.stderr.pipe(process.stderr)

    build.on('close', function (code) {
      if (0 !== code) throw new Error('node tools/build.js exited with ' + code)
      done()
    })
  })
})
```

@idleberg this is what I came up with for https://github.com/kilianc/rtail and it works

**Comment by idleberg** [comment] 2015-07-08 22:21
@kilianc Sorry for the late reply. Unfortunately, this does not work for me. What's `spawn` in your code? (I tried `gulp-spawn`)

**Comment by kilianc** [comment] 2015-07-08 23:37
@idleberg `require('child_process').spawn` look at https://github.com/kilianc/rtail/blob/develop/gulpfile.js#L69

**Comment by idleberg** [comment] 2015-07-09 06:30
@kilianc This is great, thanks a lot!

**Comment by Sannis** [comment] 2015-07-27 22:02
@idleberg, is @kilianc snippet solved your problem?

**Comment by idleberg** [comment] 2015-07-27 22:32
Yes, thank you! You should think about using that yourself or at least reference it in the Wiki

**Comment by Sannis** [comment] 2015-07-27 22:38
@isagalaev, what are you think about separate page in docs to reference all modules/packaging issues?

**Comment by isagalaev** [comment] 2015-07-27 22:40
I've lost track of this thread, to be honest, but I promise to get back to it as soon as I deal with new-styles in #348.

**Comment by danvk** [comment] 2016-04-18 18:03
It would be great if `highlight.pack.js` and `highlight.pack.min.js` were included in the NPM distribution.

Some reasons to do this:

1. Bower [has been having some issues][1] and it's not entirely clear what its future is.
1. The highlight.js bower component [isn't always updated][2] when there are new releases. (It's missing 9.3.0 at the moment.) The NPM package is updated more reliably.
1. Many other frontend packages publish their build artifacts via NPM. For example, if you `npm install jquery`, you'll get `node_modules/jquery/dist/jquery.min.js` and friends.

[1]: http://bower.io/blog/2015/bower-alive-looking-contributors/
[2]: https://github.com/components/highlightjs/releases

**Comment by derhuerst** [comment] 2016-04-18 18:35
@danvk There is also downsides:

- There is [Browserify](http://browserify.org/) and [Webpack](https://webpack.github.io/). They have become the de facto standard in Frontend programming, bundling every `require`d dependency automatically.
- Bundling dist files makes NPM packages heavier. Given the nature of deep & wide dependency trees in the JS world, this weighs in significantly.
- [A lot of other projects use highlight.js](https://www.npmjs.com/browse/depended/highlight.js), [not only on the client side](https://github.com/isagalaev/highlight.js/issues/1086#issue-134898881). For these, bundles are unnecessary weight.
- NPM hast `install` hooks to build stuff on install if that is required. NPM packages with large data sets and/or binaries do this.

**Comment by danvk** [comment] 2016-04-18 19:21
The points about browserify/webpack and the weight of the module are well-taken. I'd just point out that other extremely popular libraries (underscore, jQuery, d3) have considered these same issues and reached the opposite decision.

re: post-install hooks, `tools/build.js` isn't included in the published NPM package, so generating this file would require some contortions.

**Comment by donny-dont** [comment] 2016-04-30 17:38
Is there a reason that the `tools` dir isn't included in the NPM package @isagalaev? Running a build script is fine by me I just want to make sure I have the latest and greatest.

**Comment by isagalaev** [comment] 2016-04-30 18:19
@donny-dont if you want to build from source, just grab the source from GitHub. I don't see much sense in duplicating the source inside a production package.

**Comment by reyostallenberg** [comment] 2016-10-16 20:35
But you could publish the buid/minified files in the published NPM package so evey npm user could load it in their system without using the cdn version

**Comment by noraj** [comment] 2019-12-11 17:41
@isagalaev 
I'm using a static website generator, I'm using Gulp to copy the assets from `node_modules`, build stuff etc. But
1. I don't want to use an external version of the JS (ex: CDN)
2. I can't build it from npm package since the build tool is not shipped in it

Of course `highlight.pack.js` should not be included in the npm package for the reasons mentioned in previous comments but providing the build tool will allow anyone to build it (the pack file) in Gulp or Grunt tasks and automate the process like for all other npm package. Having to clone the source repo to build it make the automating process unnecessary more difficult.

**Comment by yyyc514** [comment] 2019-12-11 23:30
Related:

- https://github.com/highlightjs/highlight.js/issues/2061
- https://github.com/highlightjs/highlight.js/issues/2248

You might be right, but I'm starting to think the opposite solution is correct.  Both the JS distributable and the NPM are "built from source", so we are currently only distributing distributabled assets, with the original source code being on GitHub.  

- The CDN distributes the "cooked" web-usage library
- The NPM distributes the "cooked" node library

This makes sense to me.

The issue seems to be that a lot of people use npm for versioning static assets... so it seems we really need:

- The CDN distributes the "cooked" web-usage library
- The NPM distributes the "cooked" node-usage library
- NPM also distributes the "cooked" web-usage library
- The source remains on GitHub.

That seems to answer what MOST people are asking for I think.  With version 10 I was planning on throwing in a pre-built minified "common" build and see if that helps.

Nothing will likely change here until post 10.0 anyways (I'd like the next release to be 10.0) since any changes to the build process are most likely going to be built on top of the new build system, not the old one.

**Comment by yyyc514** [comment] 2019-12-11 23:44
I see some big advantages to keeping NPM as a built deliverable rather than raw source files (which might be a possibility in the future).  People using the raw GitHub repo to build with should be uncommon (correct me if you think I'm wrong).

Having it as a built asset allows us to make larger behind the scenes changes to how the library is written and structured while still providing the same old "npm API" (same file path locations, mostly same deliverable structure, etc).  This ensures stability for those using npm normally, and also allows us to iterate faster with the core library.

I'm not sure we want to encourage a lot of people to use the raw source if they don't truly need to... in my experience what people do then is hook into it in custom ways that make their project and ours project more fragile (for new releases).  I'm not speaking ill of anyone here (and indeed this is all OSS, so awesome), just pointing out that this results in more maintenance time on both sides, increases the likelihood of bugs, etc...

And often many of the things I see being done could be done better with a standardized plugin API (which we're pursuing).

Those are my thoughts.

---

IF we shipped a cooked "packed" "binary" with the NPM... what do you see as the big disadvantage to that vs including TWO full copies of the source, cooked and raw...?

**Comment by yyyc514** [comment] 2019-12-14 15:44
@noraj Is there some reason why the static CDN build doesn't work for you:

https://github.com/highlightjs/cdn-release

Fetch it once, done.

**Comment by noraj** [comment] 2019-12-14 15:52
Because it's for a project that need to work offline and that need to be self-contained, so I need all the assets locally.

**Comment by yyyc514** [comment] 2019-12-14 20:28
> Because it's for a project that need to work offline and that need to be self-contained, so I need all the assets locally.

Why couldn't/wouldn't you just vendor it into a directory of your choice (from the CDN url or from the CDN repo) and then only download the file if it was missing?  So after the very first run to build your project would work just fine entirely offline.

**Comment by yyyc514** [comment] 2019-12-14 20:30
I think what some people want is for `cdn-release` to just be packaged up into a NPM package called `highlights-assets` or something...

- If you want to use Highlight.js server-side, use `highlight-js` package
- If you want to use Highlight.js assets client-side, use `highlight-js-assets` package

Thoughts? That kind of makes sense to me.  What I'm less sure about is merging both into a single large repo.

@marcoscaceres Do you have any thoughts on how other npm packages do this? Packages whose client code is DIFFERENT than their server code and who have reasons for using both in various contexts?

**Comment by marcoscaceres** [comment] 2019-12-17 11:31
Hmm... I don't know actually. That's a good question, but I don't know what to suggest.

**Comment by yyyc514** [comment] 2019-12-17 13:11
I was kind of hoping there was some convention everyone else is doing (that makes sense) that we could just point to and follow. :-)  I feel like we're unique by having two "targets" (browser and node.js) and that makes us different than a lot of the simpler examples I've seen (so far).

**Comment by marcoscaceres** [comment] 2019-12-17 23:30
The only similar ones I can think of is projects that ship with a "-cli"... like babel and babel-cli. So you can get the babel library, and you can get the command line tool separately?

**Comment by noraj** [comment] 2019-12-21 18:23
I see an example: FA.
They have only one repository for free fonts https://github.com/FortAwesome/Font-Awesome

But they have several npm packages in https://www.npmjs.com/~robmadole

- @fortawesome/fontawesome-free-solid
- @fortawesome/fontawesome-free-brands
- @fortawesome/fontawesome-free-regular
- @fortawesome/fontawesome-free-webfonts

Those packages are deprecated and now move into:

- @fortawesome/fontawesome-free
- @fortawesome/ffree-solid-svg-icons
- etc.

By taking a look at https://github.com/FortAwesome/Font-Awesome/blob/master/UPGRADING.md#50x-to-510 you can see they are using something called npm scope

More about scope:

- [About scopes](https://docs.npmjs.com/about-scopes)
- [Creating and publishing scoped public packages](https://docs.npmjs.com/creating-and-publishing-scoped-public-packages)

Also look at their way to store multiple npm packages in one single git repository: https://github.com/FortAwesome/Font-Awesome/tree/master/js-packages/%40fortawesome

I hope this could help.

---

Totally different subject: [Configuring npm for use with GitHub Packages](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages)

**Comment by yyyc514** [comment] 2019-12-21 20:29
@noraj Interesting, but how is that directly comparable?  The problem is we have two (at least) entirely different deliverables... the browser/CDN build and the node.js build.  Currently our npm is the node build.

Isn't font awesome really just all client-side resources?  IE, it's more like our CDN build... simply publishing the CDN build onto npm under another name was one of the ideas mentioned above.

**Comment by noraj** [comment] 2019-12-22 01:34
> @noraj Interesting, but is that directly comparable? The problem is we have two (at least) entirely different deliverables -- packaged very differently... the browser/CDN build and the node.js build. Currently our npm is the node build.

Yep. I thought you wanted to make it like that:

> * If you want to use Highlight.js server-side, use `highlight-js` package (for node)
> 
> * If you want to use Highlight.js assets client-side, use `highlight-js-assets` package (for browser/CDN)

One npm package per usage/target. So just add in the git repository a structure like that:

```
hljs
└── js-packages
    └── @highlightjs
        ├── highlight-js
        │   └── package.json
        └── highlight-js-assets
            └── package.json
```

Where `@highlightjs` is the npm scope. Then you can use symbolic links to point some already existing files from the root git repository into each package sub-directory or build them with a gulp task for exemple in case of the webpack for the browser/CDN package.

So no it's not **totally** comparable to FA but most of the packaging and delivery idea is here The only difference is that they package logically different stuff and you want to package the "same" stuff for two different targets with some variances.

**Comment by yyyc514** [comment] 2019-12-22 02:01
> Yep. I thought you wanted to make it like that:

Not sure but that's what I'm leaning towards.

> So just add in the git repository a structure like that:

I don't think we should add build artifacts to our repository though... I'm not sure what's with that as a trend.  I see some advantages but also seems a very annoying thing.  We already had the chance to do that with our CDN assets and the original author chose to make a whole separate repo, so I'd say he probably agrees. :-)

**Comment by rajsite** [comment] 2019-12-23 00:30
Following up on https://github.com/highlightjs/highlight.js/issues/678#issuecomment-72732720

If a `package.json` was included in https://github.com/highlightjs/cdn-release that would work well enough for a personal project I'm working on. The `package.json` can be dead simple, just needs a name and version.

As an example I forked cdn-release, and created a new branch from tag `9.17.1` called `9.17.1-with-package`: https://github.com/rajsite/cdn-release/tree/9.17.1-with-package

The `package.json` content was:
```json
{
  "name":"@rajsite/highlightjs-cdn-release",
  "version": "0.0.1",
  "private": true
}
```
Where the name I'm using is under a public scope I own (`@rajsite`) so it won't accidentally conflict elsewhere.

Then I was able to add it to a project using:
```
npm install git://github.com/rajsite/cdn-release.git#9.17.1-with-package
```

For what it's worth, I would still prefer a `/dist` folder in the highlight.js npm package or a separate npm package with the cdn output. I wouldn't use a git based dependency like this for a work project (we have tools to cache public registry packages it would not mesh well with) and it would be a uncommon transitive dependency for other projects to rely on.

**Comment by yyyc514** [comment] 2019-12-23 01:05
> For what it's worth, I would still prefer a /dist folder in the highlight.js npm package or a separate npm package with the cdn output. I wouldn't use a git based dependency like this for a work project 

What if we pushed the CDN repo to npm ourselves under another name (`highlightjs-assets`, etc), would that not be a good resolution?

**Comment by rajsite** [comment] 2019-12-23 01:26
> > For what it's worth, I would still prefer a /dist folder in the highlight.js npm package or a separate npm package with the cdn output. I wouldn't use a git based dependency like this for a work project
> 
> What if we pushed the CDN repo to npm ourselves under another name (`highlightjs-assets`, etc), would that not be a good resolution?

That would make sense to me. It would be nice if the versions matched and LICENSE + README were included as well (a License file is missing right now from what I can tell).

Right now from cdn-release I'm pulling in the min plus a couple of additional languages as separate JS files from cdn git. It's not perfect for code size / number of network requests but helps with getting started and kicking the tires.

separate npm package sounds great! 👍

**Comment by yyyc514** [comment] 2019-12-23 01:32
> That would make sense to me. It would be nice if the versions matched and LICENSE + README were included as well 

You mean in the `build` folder or on the literal CDN?

**Comment by rajsite** [comment] 2019-12-23 01:38
In the `hightlightjs-assets` npm package similar to the [highlight.js npm package](https://unpkg.com/browse/highlight.js@9.17.1/) today, ie:
```
/package.json
/README.md
/LICENSE
/build/hightlight.js
...
```

**Comment by yyyc514** [comment] 2019-12-23 01:41
Well the actual NPM package is in `build`, not the root of the repo... so if we added those files to the package/build that's where they'd end up, not root.

Although we could probably add a root license... a simple PR would probably resolve that. ;-)

**Comment by yyyc514** [comment] 2020-03-17 03:19
This is considered resolved by:

https://www.npmjs.com/package/@highlightjs/cdn-assets

If you really want your pre-compiled assets from NPM (whether via npm/yarn or https://unpkg.com or something else) vs some other method, `cdn-assets` is how you should get them.

**Closed by yyyc514** 2020-03-17 03:19 UTC
Labels: package/build

**Comment by rajsite** [comment] 2020-03-17 05:45
Worked great for me! Thanks! :D
