### ISSUE TITLE
(Python) unhighlighting the function calling

### ISSUE THREAD

**Issue by MohamedAli00949** [highlightjs/highlight.js#3896] opened 2023-10-21 08:06 UTC
**Describe the issue**

I have called the `testFirstChar` function to get some of the text and print it.

**Which language seems to have the issue?**

Python

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**

This is the code sample
```
def testFirstChar(text = "", char = ""):
    if len(text) > 0 and text[0] == char: 
        return "Nice"
    else: 
        return "bad"

print(testFirstChar())
print(testFirstChar("dsafdsa", "d"))
```
you can show also it at https://jsfiddle.net/MohamedAli00949/ys4z7t09/7/

**Expected behavior**

You can see in this screenshot that a called function at the print didn't highlight.

![Screenshot 2023-10-21 103143](https://github.com/highlightjs/highlight.js/assets/76850143/898703ba-e420-4735-88fc-c2bf1d21b715)

**Comment by joshgoebel** [comment] 2023-10-21 13:11
Highlighting function invocation isn't supported for all grammars yet.  We don't leave individual issues open per language for things like this, so this will be closed as a duplicate of #2500. PRs to add this support to any of our grammars would always be welcome.

**Closed by joshgoebel** 2023-10-21 13:11 UTC
Labels: language, bug, help welcome
