### ISSUE TITLE
[HTML] An `em` tag nested under a `span` tag is parsed incorrectly or unexpectedly.

### ISSUE THREAD

**Issue by wulechuan** [highlightjs/highlight.js#3059] opened 2021-03-20 12:02 UTC
**Describe the issue**

For a given `HTML` code block, an `em` tag nested under a `span` tag is parsed incorrectly or unexpectedly. A normal letter/character "after/outside" the `em` tag is unexpectedly parsed as an "`hljs-name`".

**Which language seems to have the issue?**

`HTML`

**Are you using `highlight` or `highlightAuto`?**

Yes, indirectly, via the `markdown-it-hightlightjs` package.

**Sample Code to Reproduce**

Try js codes shown below, here: [https://npm.runkit.com/markdown-it-highlightjs](https://npm.runkit.com/markdown-it-highlightjs) .

```js
const MarkdownIt = require('markdown-it')
const markdownItHighlightjs = require("markdown-it-highlightjs")

const markdownItParser = new MarkdownIt({chtml: true })
markdownItParser.use(markdownItHighlightjs)

const htmlString = markdownItParser.render('```html\n<span>A<em>B</em>C</span>\n```\n\n')
console.log('HTML string: ' + htmlString)
```

**Actual output**

```html
<pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">span</span>&gt;</span>A<span class="hljs-tag">&lt;<span class="hljs-name">em</span>&gt;</span>B<span class="hljs-tag">&lt;/<span class="hljs-name">em</span>&gt;<span class="hljs-name">C</span></span><span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span>
</code></pre>
```

For a bit better human readability, I delibratedly insert some indetantions and blank lines to the actual output, then it looks like:

```html
<pre>
    <code class="hljs language-html">

        <span class="hljs-tag">&lt;
            <span class="hljs-name">span</span>
            &gt;
        </span>
        
        A
        
        <span class="hljs-tag">
            &lt;
            <span class="hljs-name">em</span>
            &gt;
        </span>
        
        B
        
        <span class="hljs-tag">
            &lt;/
            <span class="hljs-name">em</span>
            &gt;
        
            <span class="hljs-name">C</span> <!-- ********** incorrect or unexpected ********** -->
        </span>
    
        <span class="hljs-tag">
            &lt;/<span class="hljs-name">span</span>
            &gt;
        </span>

    </code>
</pre>
```

**Expected output**

```html
<pre><code class="hljs language-html"><span class="hljs-tag">&lt;<span class="hljs-name">span</span>&gt;</span>A<span class="hljs-tag">&lt;<span class="hljs-name">em</span>&gt;</span>B<span class="hljs-tag">&lt;/<span class="hljs-name">em</span>&gt;</span>C<span class="hljs-tag">&lt;/<span class="hljs-name">span</span>&gt;</span></code></pre>
```

The letter "C" is expected to be a normal text instead of being wrapped by the `<span class="hljs-name">` tag.

**Comment by joshgoebel** [comment] 2021-03-20 12:46
Closing as a duplicate of #3044.  This has already been resolved in main. https://github.com/highlightjs/highlight.js/commit/3ec4c1ec3c70814ad91ceee68f58dbbed6ace740

**Closed by joshgoebel** 2021-03-20 12:46 UTC
Labels: bug, help welcome, language
