### ISSUE TITLE
Low-level API

### ISSUE THREAD

**Issue by be5invis** [highlightjs/highlight.js#1493] opened 2017-04-12 12:24 UTC
Currently I am going to write something similar to Andres Löh’s [lhs2TeX](https://www.andres-loeh.de/lhs2tex/), which is a tool that analyzes your source code and, layout them in print-level outputs (using proportional fonts and tables to enforce alignment). The output may look like this:

![image](https://cloud.githubusercontent.com/assets/240091/24957308/dde5eb76-1fbd-11e7-86b8-f2bd5486fc58.png)

However I found there is no way to extract low-level information about the tokens and ranges parsed by HLJS, which makes it impossible to do further layouting (i.e., analyzing alignments and form `<table>`s to place them).

**Comment by samvv** [comment] 2017-06-21 12:44
Yes, I would definitely be a proponent of this. It would enable me to write a syntax highlighter for the terminal, which is virtually impossible to do so now (the only package I could find was [cli-highlight ](https://github.com/felixfbecker/cli-highlight) but it [does not support all languages](https://github.com/felixfbecker/cli-highlight/issues/1)).

**Comment by fcarreiro** [comment] 2017-07-15 11:40
I had exactly the same thoughts as you guys, for the same reason as @samvv. I was thinking of looking at the code to see what has to be changed to allow for a more low-level API.

Without yet having looked at it i think that, for terminal highlighting, it would probably be enough to have something like an array of `(word, identifier)`; then identifier (variable, keyword, etc) can be mapped to colors with a theme. Later the HTML rendered would put HTML tags around those, and the terminal renderer would output a text decorated with the `colors` or `chalk` packages.

What do you think?

Do you think the three of us could make a team effort out of this?

I also wonder if this is something the community would accept to merge, since it's a change in the architecture, even if we make the default usage non-breaking and falling back to HTML.

**Comment by samvv** [comment] 2017-07-15 12:05
@fcarreiro Looks like a good idea. Performance-wise it will be very fast. I'd be definitely willing to help, but I am already quite occupied with a lot of projects so I'm not sure I will be of much use. As for the merging, this would indeed mean severe changes that the maintainers might not be willing to accept.

**Comment by fcarreiro** [comment] 2017-07-15 12:07
Thanks. Maybe we should ping @Sannis (the only maintainer I've seen around) to comment on this?

**Comment by yyyc514** [comment] 2019-10-10 16:33
Closing this as a duplicate of https://github.com/highlightjs/highlight.js/issues/1086 which has more discussion in the thread there.

**Closed by yyyc514** 2019-10-10 16:33 UTC
