### ISSUE TITLE
javascript code are treated as comment

### ISSUE THREAD

**Issue by 274659281** [highlightjs/highlight.js#1506] opened 2017-04-27 10:52 UTC
My javascript code are treated as comment. The code and screenshot are in the attach files.
Please help!

[Desktop.zip](https://github.com/isagalaev/highlight.js/files/961319/Desktop.zip)

**Comment by yyyc514** [comment] 2019-10-07 10:36
Ok, I'm not downloading a zip file, sorry.  If you're still having issues please upload sample code, a screen grab, etc.  If you want to show a reproducible test case please consider jsfiddle:

Simple template you can fork:
https://jsfiddle.net/ajoshguy/nagkqytv/11/

**Comment by yyyc514** [comment] 2019-10-07 10:37
Closing due to age (we're trying to clear out old dead issues), but we can reopen if you provide additional details and are still having trouble.

**Closed by yyyc514** 2019-10-07 10:37 UTC
