### ISSUE TITLE
(Lua) Block comments gets the same className as inline comments

### ISSUE THREAD

**Issue by DiegoJArg** [highlightjs/highlight.js#3669] opened 2022-12-02 18:39 UTC
**Describe the issue**
I invoked marked to parse all text inside .hljs-comments as markdown.
It works.
My goal was to target multiline comments.
But comments at the side of the code, inline-comments have the same className.
Therefore, it is imposible to apply different style to not disturb the code.

**Which language seems to have the issue?**
I have tested it with Lua, but just guessing, any language with full-line or multiline comment would have the same className as inline comments.

**Are you using `highlight` or `highlightAuto`?**
highlight

**Sample Code to Reproduce**
```
--[[
# Hello, [Lua](http://www.lua.org) ! [Why?](https://www.youtube.com/watch?v=H3inzGGFefg)
- [Manual Online](http://www.lua.org/manual/), [5.4 EN](http://www.lua.org/manual/5.4/manual.html), [5.1 ESP](http://www.lua.org/manual/5.1/es/manual.html)
- Scripting, 
- Portability, 
- Small Size/Footprint, 
- Simplicity, 
- MIT License
]]

print(_VERSION)
print( type("Hello world") ) --> string
print( type(10.4*3) )        --> number
print( type(print) )         --> function
print( type(type) )          --> function
```

```
<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
<script>
window.addEventListener('DOMContentLoaded', function() {
    console.log('Highlighting All');
    hljs.highlightAll();
    console.log('Markdown in comments');
    var hljs_comment_elements = document.getElementsByClassName('hljs-comment');
    Array.prototype.forEach.call( hljs_comment_elements, function(e){
      mdcomment = e.innerHTML;
      e.innerHTML = marked.parse( mdcomment.trim() );
    } )
});
</script>
```

**Expected behavior**
Inline comments should get a different className, than comments that have a dedicated line for themselves.
Styles for spacing, like padding and margin would apply different.

**Additional context**
In the next example, there is an space between each print(), which is caused by css and a paragraph tag inserted by marked, which I can't get rid off. 
I passed to marked all .hljs-comments classed tags.

![image](https://user-images.githubusercontent.com/25246225/205363017-671da299-fbc8-4c41-9a81-845c60f26430.png)

**Comment by joshgoebel** [comment] 2022-12-02 23:53
> Inline comments should get a different className, than comments that have a dedicated line for themselves.

A PR for this would be welcome if you'd like to contribute, I'm opening to using our new nested scopes for this, such as `comment.line` and `comment.block`... just no one has gotten around to it yet.

Closing this as a duplicate of #2500.

**Closed by joshgoebel** 2022-12-02 23:53 UTC
Labels: language, bug, help welcome
