### ISSUE TITLE
(jsx) multiple self-closing tags with attributes highlighting broken

### ISSUE THREAD

**Issue by leafOfTree** [highlightjs/highlight.js#1915] opened 2018-11-28 03:58 UTC
Given jsx code:
```javascript
class App extends Component {
  render() {
    return (
      <BrowserRouter>
        <div>
          <Route path="/about" component={About} />
          <Route path="/contact" component={Contact} />
        </div>
      </BrowserRouter>
    );
  }
}
```

![2018-11-28_114855](https://user-images.githubusercontent.com/13349592/49127968-5e298c00-f304-11e8-9c4e-23ae61f4a59e.png)

It seems that the XML code is not highlighted because of the second `Route` tag with attributes.
When I tried to modify `src/language/javascript.js`
```diff
          { // E4X / JSX
            begin: /</, end: /(\/\w+|\w+\/)>/,
            subLanguage: 'xml',
            contains: [
              {begin: /<\w+\s*\/>/, skip: true},
              {
-               begin: /<\w+/, end: /(\/\w+|\w+\/)>/, skip: true,
+               begin: /<\w+/, end: /(\/\w+[^>]*|\w+\S*\s*\/)>/, skip: true,

                contains: [
                  {begin: /<\w+\s*\/>/, skip: true},
                  'self'
                ]
              }
            ]
          }

```
The highlighting works as expected.

![2018-11-28_115530](https://user-images.githubusercontent.com/13349592/49128008-8b763a00-f304-11e8-9f0b-e95df2925861.png)

**Comment by JeromeLin** [comment] 2018-12-26 09:35
@leafOfTree use your config have wrong still. e.g

**Comment by leafOfTree** [comment] 2018-12-27 04:02
@JeromeLin Regexp need to be updated:
```diff
          { // E4X / JSX
            begin: /</, end: /(\/\w+|\w+\/)>/,
            subLanguage: 'xml',
            contains: [
              {begin: /<\w+\s*\/>/, skip: true},
              {
-               begin: /<\w+/, end: /(\/\w+|\w+\/)>/, skip: true,
+               begin: /<\w+/, end: /(\/\w+\S*|\w+\S*\s*\/)>/, skip: true,

                contains: [
                  {begin: /<\w+\s*\/>/, skip: true},
                  'self'
                ]
              }
            ]
          }
```
Then the code is highlighted correctly:
![2018-12-27_115922](https://user-images.githubusercontent.com/13349592/50464940-f16ee380-09ce-11e9-8c2a-2e9c331a8e4c.png)

**Comment by JeromeLin** [comment] 2018-12-28 02:39
@leafOfTree

**Comment by leafOfTree** [comment] 2018-12-29 02:48
@JeromeLin 
```diff
          { // E4X / JSX
            begin: /</, end: /(\/\w+|\w+\/)>/,
            subLanguage: 'xml',
            contains: [
              {begin: /<\w+\s*\/>/, skip: true},
              {
-               begin: /<\w+/, end: /(\/\w+|\w+\/)>/, skip: true,
+               begin: /<\w+/, end: /(\/\w+[^>]*|\w+\S*\s*\/)>/, skip: true,

                contains: [
                  {begin: /<\w+\s*\/>/, skip: true},
                  'self'
                ]
              }
            ]
          }

```

**Comment by JeromeLin** [comment] 2019-01-02 06:51
![1546411817617](https://user-images.githubusercontent.com/9812721/50582471-c1778280-0e9d-11e9-8822-58ae0fdb26ca.jpg)

```js
import { SwipeAction, Button, Cell } from 'zarm';

class Demo extends React.Component {
  render() {
    return (
      <div>
        <SwipeAction
          right={[
            <Button size="lg" theme="primary" onClick={() => console.log('右按钮1')}>右按钮1</Button>,
            <Button size="lg" theme="error" onClick={() => console.log('右按钮2')}>右按钮2</Button>,
          ]}
        >
          <Cell>左滑看看</Cell>
        </SwipeAction>

        <SwipeAction
          left={[
            <Button size="lg" theme="primary" onClick={() => console.log('左按钮1')}>左按钮1</Button>,
            <Button size="lg" theme="error" onClick={() => console.log('左按钮2')}>左按钮2</Button>,
          ]}
        >
          <Cell>右滑看看</Cell>
        </SwipeAction>

        <SwipeAction
          autoClose
          left={[
            <Button size="lg" theme="primary" onClick={() => console.log('左按钮1')}>左按钮1</Button>,
            <Button size="lg" theme="warning" onClick={() => console.log('左按钮2')}>左按钮2</Button>,
          ]}
          right={[
            <Button size="lg" theme="error" onClick={() => console.log('右按钮1')}>右按钮2</Button>,
          ]}
          onOpen={() => console.log('open')}
          onClose={() => console.log('close')}
        >
          <Cell>左右都能滑动（自动关闭）</Cell>
        </SwipeAction>
      </div>
    )
  }
}

ReactDOM.render(<Demo />, mountNode);
```

**Comment by leafOfTree** [comment] 2019-01-08 06:42
@JeromeLin JSX attr is handled by XML syntax, so `src/language/xml.js` can be modified like below to get JSX attr expression syntax highlight

```diff
  var TAG_INTERNALS = {
    endsWithParent: true,
    illegal: /</,
    relevance: 0,
    contains: [
+      {
+        className: 'jsx-attr',
+        begin: /={/,
+        end: /}/,
+        subLanguage: 'xml',
+      },
      {
        className: 'attr',
        begin: XML_IDENT_RE,
        relevance: 0
      },
```

![2019-01-08_144027](https://user-images.githubusercontent.com/13349592/50814085-6c32e980-1353-11e9-8bf6-72695dc4899b.png)

**Comment by yyyc514** [comment] 2019-10-07 09:00
I just commented over in the other thread:

> If someone wants to take a swing at a PR you want to focus on:

> https://github.com/highlightjs/highlight.js/blob/master/src/languages/javascript.js#L155

The reuse of sublanguage xml also sounds like a nifty idea. (though that might be doing a little TOO much, honestly)

**Comment by yyyc514** [comment] 2019-10-07 09:11
https://github.com/highlightjs/highlight.js/issues/1625 reminded me that it's not JUST HTML inside these blocks, but you can have JS style comments, template variables, etc... 

The more I read the more it seems a separate JSX grammar might be the right choice for dealing with all of this.

**Comment by zwhitchcox** [comment] 2019-12-13 17:35
I am also having this issue. How exactly would I go about fixing this? Is there a contribution guide?

I cloned the repo, but there is not start script or obvious way to set up the development environment.

**Comment by zwhitchcox** [comment] 2019-12-13 17:36
Also, I don't know if this is useful, but this is a minimum reproduction of the bug

```tsx
const n = () => <X />
const m = () => <X x="" />
```

**Comment by yyyc514** [comment] 2019-12-13 21:35
Well it's all Node.js... you can build a new library with:

```
node ./tools/build.js -t node
```

Run tests:

```
npm run test
```

I'd start by adding a new expects test in `tests/markup/js` (look at other languages for example)... to get a failing test case. Then you'd have to work on the language grammar until you fix the bug.

**Comment by yyyc514** [comment] 2019-12-13 21:37
The JSX stuff is around line 190 or so in the grammar.

**Comment by yyyc514** [comment] 2019-12-13 21:44
So it looks like we're only trying to find the beginning and end of the tags and then let XML do the highlighting... which makes sense... I haven't looked at this closely before so I"m not sure what is going wrong here.  These regexes are way more complex than they need to be though at first glance.

**Comment by yyyc514** [comment] 2019-12-13 22:24
If anyone wants to test that, that'd be great.

**Comment by yyyc514** [comment] 2019-12-13 22:26
Really we should make sure the begin and end tags are actually paired, but we can't do that yet...

**Comment by yyyc514** [comment] 2019-12-14 11:49
@leafOfTree 

```diff
+      {
+        className: 'jsx-attr',
+        begin: /={/,
+        end: /}/,
+        subLanguage: 'xml',
+      },
```

Actually technically isn't the sublanguage we should use `javascript`?  The {} just allowed you to include javascript (event handlers, etc) which could also be more JSX code... correct?

**Comment by yyyc514** [comment] 2019-12-14 23:18
I've added both these as test cases (and they pass):

```js
const n = () => <X />
const m = () => <X x="" />
```

```js
class App extends Component {
  render() {
    return (
      <BrowserRouter>
        <div>
          <Route path="/about" component={About} />
          <Route path="/contact" component={Contact} />
        </div>
      </BrowserRouter>
    );
  }
}
```

They both are good examples of the tag closing issue I think.  The other larger example has more to do with `{}` and inlining code than tags - and we need to treat that as a separate (more complex) issue.

The larger example is likely parsed better than before, but it still gets confused about the attribute highlighting since it doesn't understand the inline `{}` stuff.

**Comment by yyyc514** [comment] 2019-12-15 12:34
Opening a new issue to track the issues with `{}` separate from the issues with tag closing.

**Closed** 2019-12-15 17:35 UTC
Labels: bug, help welcome

**Comment by leafOfTree** [comment] 2019-12-16 02:29
Thanks for tracking these jsx issues. 

> @leafOfTree
> 
> ```diff
> +      {
> +        className: 'jsx-attr',
> +        begin: /={/,
> +        end: /}/,
> +        subLanguage: 'xml',
> +      },
> ```
> 
> Actually technically isn't the sublanguage we should use `javascript`? The {} just allowed you to include javascript (event handlers, etc) which could also be more JSX code... correct?
> 
> And can't `{}` truly be used anywhere, not just for attributes?

You are right about the `{}`. I know a little about `highlight.js` and I used `xml` as sublanguage beacuse `src/language/javascript.js` uses `sublanguage: xml` for jsx and it seems to work.
