### ISSUE TITLE
No colors for `bash` and `shell` 

### ISSUE THREAD

**Issue by ericis** [highlightjs/highlight.js#1926] opened 2018-12-13 07:14 UTC
Attempted to create an example for `bash` and `shell` highlighting, but the latest version does not show any colors (grey background with black text): http://plnkr.co/edit/smWejiNw2dNd5QjrmZzm?p=preview

However, the highlight.js website shows colors somehow??

**Comment by egor-rogov** [comment] 2019-01-04 22:18
I'm closing this as there was no reply. Feel free to reopen in case something left unanswered.

**Closed by egor-rogov** 2019-01-04 22:18 UTC

**Comment by bric3** [comment] 2020-06-30 13:18
For reference I actually had to load the `shell` language, in order to access the feature. 

Highlight JS 10.1.1

**Comment by yyyc514** [comment] 2020-07-01 07:42
"shell" is definitely included in the latest CDN builds:

https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js

**Comment by bric3** [comment] 2020-07-02 11:10
Yes but I needed to load the language as well in order to have `shell` highlighting to kick in, maybe there's somthing wrong in my setup. Byt this goes over my competences in JS.

**Comment by yyyc514** [comment] 2020-07-02 13:15
I don't see why that would be.  Bash and Shell are both included in the default/common build - unless you're using a custom build without them.  If you can reproduce a standalone jsfiddle that shows you issue you can file an issue and I'd be happy to take a look.

**Comment by bric3** [comment] 2020-07-02 16:45
@yyyc514 I'll see what I can come up with tomorrow.

**Comment by yyyc514** [comment] 2020-07-02 17:04
For simple tests you can fork https://jsfiddle.net/ajoshguy/2bmdswn6/4/

**Comment by bric3** [comment] 2020-07-04 21:17
@yyyc514 It turns out I cannot reproduce. Maybe I was too tired and missed something before. Indeed shell language works with the default build. It was a hugo template error in the theme.
