### ISSUE TITLE
Please release 9.15.4 on npm repository

### ISSUE THREAD

**Issue by gabrielts** [highlightjs/highlight.js#1991] opened 2019-02-25 20:15 UTC
Please release 9.15.4 on https://npmjs.com/package/highlight.js

**Comment by DarylThayil** [comment] 2019-02-25 20:17
+1 this is breaking our builds

**Comment by nicksp** [comment] 2019-02-25 20:21
+ 1 still getting the same build error as described in https://github.com/highlightjs/highlight.js/issues/1984

Can't proceed with development. The lib I'm using depends on `^9.12.0` version, unfortunately, which fails. Any updates on the fix guys?

**Comment by ben-mobify** [comment] 2019-02-25 20:49
+1

**Comment by png262** [comment] 2019-02-25 20:53
+1

**Comment by marcoscaceres** [comment] 2019-02-25 21:18
Closing as duplicate of #1984

**Comment by marcoscaceres** [comment] 2019-02-25 21:18
Please subscribe to #1984. Release coming soon.

**Closed by marcoscaceres** 2019-02-25 21:18 UTC

**Comment by corbinu** [comment] 2019-02-25 21:52
Seriously just tag 9.14.2 as latest until this is fixed. Everybody's builds could have been fixed in 5 min. We are not mad about the bug we are mad about how terribly this has been handled. It has been 16 hours and everybody's breakage could have been fixed just by changing the npm tag. Instead we are getting locked threads with political messages thrown over the wall with no ability to even respond.

**Comment by marcoscaceres** [comment] 2019-02-25 21:56
As I mentioned earlier, I don’t have rights to do that.

**Comment by corbinu** [comment] 2019-02-25 22:01
@marcoscaceres Yes and I am not blaming you for that. I choose not to comment at that time because I didn't think it would be helpful. However @isagalaev clearly took the time to write out and proofread a political statement rather than adjust the tag 5 hours ago.

**Comment by marcoscaceres** [comment] 2019-02-26 01:58
Understand your frustration. Maintaining open source software is particularly stressful because it also means managing community expectations (what @isagalaev was doing). We depend on the community to reciprocate in their support, as we do this for fun. When it’s no longer fun, well... anyway, I’m preaching to the choir I’m sure.

**Comment by isagalaev** [comment] 2019-02-26 07:05
> However @isagalaev clearly took the time to write out and proofread a political statement rather than adjust the tag 5 hours ago.

Yes, that was my choice to spend time on advancing a topic I feel strong about rather than fixing something. This is what "volunteer" means: I never signed any contract to be on-call or even maintain this code in a state that anyone could use it. You can't assume you know my (or any maintainers) motivation, and it's definitely not up to you to tell me what was more important. We don't even know each other.
