### ISSUE TITLE
Is there C-Language support ?

### ISSUE THREAD

**Issue by hiromi3** [highlightjs/highlight.js#2460] opened 2020-03-16 14:33 UTC
Hello,
The highlight.js is very useful.
There is C++ support.
But, I want to use C-Language.
Do you have any plan to support it ?

**Comment by yyyc514** [comment] 2020-03-17 02:40
**We're open to contributions.** The core team doesn't typically developer languages - that's left to the community.  C is already built-in (as part of our C++ support)... but we're open to it be improved to be C specific, but someone would need to step forward to do the work, write the tests, etc.

Closing as a duplicate of https://github.com/highlightjs/highlight.js/issues/2146

Also worth noting, for many snippets the C++ highlighting works "just fine".

**Closed by yyyc514** 2020-03-17 02:40 UTC
Labels: enhancement

**Comment by yyyc514** [comment] 2020-03-17 03:01
This is made more complex because preferably we'd like C and C++ to share a common foundation (they seem very similar parsing wise) where that make sense.  So that takes some planning and thought.  We don't just need a wholly separate C grammar.

**Comment by hiromi3** [comment] 2020-03-17 03:55
Thank you for your reply.
I could understand the situation.
So, I want to request you to add 'C-Language' class, but it acts same as 'cpp' class.
Currently, I can do as below.
`<code class="cpp hljs">`
But, in addition, I want to do as below.
`<code class="C-language hljs">`

The reason I want 'C-Language' class name is, I am using the class name string like 'cpp' in my JavaScript code.
When highlight.js detect the code as 'cpp', I am using the 'cpp' to add the title 'This is C++ sample code' above the code area.
But, hightlight.js has no 'C-Language' class, I can not distinguish C++ and C-Language.
Or, are there any other good solution?
I would appreciate your advice.

**Comment by yyyc514** [comment] 2020-03-17 03:56
Your C language is just named `c` and already exists, but it has the exact same behavior as `cpp`.

**Comment by hiromi3** [comment] 2020-03-17 03:58
Really?
It is a good news.
I will test it.

**Comment by hiromi3** [comment] 2020-03-17 05:11
It worked fine!
Thank you.
